### ISSUE TITLE
Splice takes a while to update visuals but data updates instantly

### ISSUE THREAD

**Issue by krityan** [ractivejs/ractive#3127] opened 2017-11-06 16:27 UTC
## Description:
When using ractive.splice, it takes up to 30 seconds for changes to update the DOM, however using get and set alongside array.splice is instant.

This is apparent when have a component that contains a configuration wizard component and a display component, that share data via many two-way bindings.

We have an extension that lets us inspect components, we can see that on the display component, the effects of the splice have affected the data property correctly and near instantly, however the page itself makes it look like the component hasn't updated. Doing other actions that cause the component to render new content or re-render current content make the change appear visually immediately.

There appear to be no issues with the data binding, as is shown by our inspection and the correct behaviour with array.splice. Which leads us to believe that ractive.splice isn't causing a re-render to occur that should be occurring.

We've noticed this happens in areas with nested {{#each}}'s, for example:

```
{{#each X}}
    {{#each Y}}
        {{.}}
    {{/each}}
{{/each}}
```

After doing some debugging, the removeChild calls for the display component nodes never happen until a good time after the data property containing the Y property in the above example has updated.

For further help with debugging this, is it possible to get a description of the differences between the old splice and the new one? As this was not a problem in 0.7.3, nor when using array.splice.

## Versions affected:
0.9.3

## Platforms affected:
Chrome 61, IE 11

## Reproduction:
Not 100% sure yet, this demo is close to our scenario but much simpler, I've been tweaking it to try and make it run into the same issue but have yet to find what's making it fall over [Playground Link](https://ractive.js.org/playground/#N4IgFiBcoE5SAbAhgFwKYGcUgL4BoRtIQAeMFAWwQD4AdGWgOzLSQBM6HmB6MVj+kxIAjAPZsAnpyFsAlgDcABLLYBeWoSQwA5mhQbqJbnPnTGg5hgDGMWQAcUytRrkY7yCQBlZWDYpQSdmjqhGgAHijcMEhWKApoBhaKyYrAwADErFZginzsaDAAkugUGDg4SSkkJmYpqcAAdOWVyWnUsiVlFVx1RjUt9dxZYM1cA2npdlpxSAjKnaNMvUi1dSkTw4qu7kgSxWilDR0HXQO9bkiMq2traShgPouMN8lGF1dn68BDMSPdS1VuCtxt8pjAZggnm8bPYUGYLCRrLYHE4QtsPABhUSMFBIWSMAp+AJBELoCJRGJxeQJEDXRTVHw7Lw+Rzo3b7UohNJsiQAZRQAFcAGZC04gbhmaHIuEWBFI2GojQlHboImBYJK8KRaKxeKJHpVKzYoWybQCmBobxYRRYYVCrnAW0ihpOoVWlDNcXw-QoBluTHY3H4go2wUih2uz0ShHceUOeFcREwlEqEJGxgms0W91qkma8k6qk0ukiAUoFDYxTYgC0VgQsisAGsQv6G5aWQZee420ZhGWKx9E7HkzKxkOxJJJbxKDQQAQMPAAEqU+INI0UOzYtA4jANHnuxSqRTL3XUhpa7dsAAUwEqyuQ6EgigA5Ol9yzn3hZQa2KgkE-bwNZI8jYAoOQwJ8AG0NAARg0PBFA0AAmeDEJAABmDQAF0vyArZGQ8cCoKwyp-kYHAAEoAG5vyYE8izXUQNy3Hc9wI3YsRxPECRgQ9jxXM8L0Ya9AIBe9UDQJ9Xx5Tigx4z9aOeLY-yfIUBUYXVsSvCjUgGC1BRgZ5RKUupXQAsi6gsxR8EU5J1zsMs0DYACBh5fk7QgxQ1I0uJK203S8OSeQtFDO0+PuHwGl0FAr2fV0XTDN0P2o2y1n080jM+ZJjlKJ9XU+KzkissjKJosc6IEtBGOYglWPTTNzXba0j3o1chJEgZxMfF90nq01GvdBTypM5TcVU9TNMYfzjJudLDICgEbjMxRIJIwLrIGGzhrqbF8Q6cafNkLSdJmtYIt3LS4u7KwmpQT8vIm3yppOrL-AeXdWxu2LXXugAGBCYJS9bKM2ixSsU4LeMLeI+IJAB3fjTzQG87y0aKpPSXEdD0IaxIOFVJJ6rq0FxpTKl-MaHsO46FrJlA5sy9bltOpbEvdKCNAAQVQjQACEeZADFsIKypaA9UjcIBSpdsYfaqcm6bRfLd6GkugAqc9qRxAAVUQADFZAte7vIVnTaeSMWxfTDBRAQKqEFEbRYrQLWUANi02GfIGpY9b2lJK6jcCAA) (All our components in the problem case have data functions, just forgot to include them all in the playground example)

**Comment by evs-chris** [comment] 2017-11-06 18:05
There shouldn't be any differences in splice behavior from 0.7 to 0.9, other than some speed and correctness improvements, especially related to transitions. It _sounds_ like maybe there is a race condition with a binding that eventually resolves itself or some other similar thing that hangs up the runloop, which will wait until everything is settled before removing DOM nodes.

Are you using deferred observers with twoway bindings that would affect each other, or maybe a custom transition that isn't calling `complete` in certain circumstances?

**Comment by krityan** [comment] 2017-11-06 18:38
I'll have to wait until tomorrow to look at this again, but we do use slide/fade transitions throughout our app and I'm pretty sure this area uses the fade one, so that will be what I look at first thing in the morning.

**Comment by krityan** [comment] 2017-11-07 09:02
I've looked at the areas involved and none of the areas where the dom should be modified are using transitions. I've also checked all the observers on the bindings connecting the 2 lists and none of those interfere with each other.

We've also noticed that sometimes trying to use Ractive.splice to insert something into an array causes a crash because ractive tries to call shuffle on something that doesn't have a shuffle function. We tried putting the item we're adding into an array and it didn't make a difference.

Also, if this is relevant, our display component is inserted into the DOM by using resetPartial on the overall tile component which renders a new component with a collection of bindings.

**Comment by evs-chris** [comment] 2017-11-07 14:27
Can you try it out with 0.9.9 and share any errors that are thrown in the console with their stack traces?

**Comment by krityan** [comment] 2017-11-07 15:41
This appears to be related to computed properties that have a two way binding to a data property, and the data property is spliced.

Once case where the shuffle error appears is when we try to splice an item out of a single item array computed property which is passed into another component and spliced within that component.
In this case the computed property has a getter and setter.

The stack trace we get is:
```
Uncaught TypeError: this.target.shuffle is not a function
at LinkModel.shuffle$1 [as shuffle] 
at model   
at Child.path [as splice] 
at Child.<anonymous>
at Child.caller
at notifySubscribers  
at fireEventAs
at fireEvent   
at EventDirective.fire
at HTMLSpanElement.owner.on.handler
```

Looking at other scenarios where we using ractive.splice without issue, there aren't any computed properties involved.

**Comment by evs-chris** [comment] 2017-11-07 18:35
So when you splice a computed property, are you expecting it to splice the computed array and then call the setter with the freshly spliced computed array? This is technically not a supported case right now, but I'm trying to determine exactly how it should behave.

That seems a little strange because the next invalidation of the computed will wipe out the value unless you have a bunch of code to diff the array and update the sources in the setter. Is that the case?

**Comment by krityan** [comment] 2017-11-07 18:50
Our use case is that we have component A that has the array as a computed property, it passes this to child component B which makes it a data property of component B.

Component B then splices the array to remove the value from it, previously this would just update the computed property in component A without any fuss, but now it causes the above stack trace and error.

In our case component A actually deconstructs when the object is removed since it's a singleton array utilizing a generic component, so updating the sources wouldn't be necessary. But it does point towards the original issue being linked to computed properties as there is one involved.

**Comment by evs-chris** [comment] 2017-11-07 18:58
Ah, then the issue is that 0.7 had undefined behavior in this case, which doesn't affect your code because your code doesn't care what happens after that point. As a quick workaround for the issue, you can try passing in the array as data rather than as a binding by using a static mustache e.g. `<componentB array="[[computed]]" />` rather than `<componentB array="{{computed}}" />`. That will break the link between the array value in componentB and the computed in componentA, so unless you need changes in componentA after the render of componentB to be propagated into componentB, that should eliminate the error and subsequent hang of the runloop.

I think the solution to this is to have the computed intercept the splice and turn it into a set. I'll put together a pr when I get a few spare cycles.

**Comment by krityan** [comment] 2017-11-14 09:19
Got an update regarding this, we have a periodic page refresh which was causing the update to happen. When we remove this update, the splice never leads to the DOM updating at all, apologies for the slightly misleading initial information here but I was unaware that we had that refresh.

**Comment by evs-chris** [comment] 2017-11-14 20:59
Based on the stack track, I'm pretty sure this is fixed on edge. If you can, try your app out with an edge build and re-open this issue if it's not fixed. Thanks!

**Comment by krityan** [comment] 2017-11-27 12:24
Just tried with build: 1.0.0-build-105

The splice is still not causing the DOM to update.

**Comment by evs-chris** [comment] 2017-11-28 05:22
I'm not really sure where else to look for the issue. Can you create an example the exhibits the incorrect behavior?

**Comment by krityan** [comment] 2017-11-28 09:12
There's clearly something I'm missing, I'm going to dig into this a bit more then get back to you, since this is also happening with push. Small scale scenarios aren't reproducing the same effect and some instances of splice/push are working just fine.

To be honest, this is incredibly difficult to debug as the data is updating correctly on the component, and making another change that affects the table such as enabling/disabling headers causes the DOM to immediately reflect the data. The fact that set also immediately updates the DOM suggests it's related to the new implementations of splice etc? Based on that, this may be related to #3093

**Comment by krityan** [comment] 2017-11-28 09:48
I just realised that 2 errors have sort of merged into one conversation here.

With regards to the stack trace error, on edge the error is no longer showing in the console but the item is not removed from the array.

The above comment is related to the DOM not updating error.

**Comment by evs-chris** [comment] 2018-04-24 20:50
0.10 has pretty significantly reworked shuffling, so I'm going to close this. Please don't hesitate to reopen if the issue isn't resolved.

**Closed as completed by evs-chris** 2018-04-24 20:50 UTC
Labels: enhancement/performance
