### ISSUE TITLE
[question] how to use sub component's data in computed properties

### ISSUE THREAD

**Issue by magicdawn** [ractivejs/ractive#2349] opened 2016-01-20 09:58 UTC
in jsfiddle: https://jsfiddle.net/magicdawn/umtuw00e/

I want to access `Sub` age in `Comp`, but seems like in `Comp`'s  compute property, `this.findComponent` fails.

**Comment by fskreuz** [comment] 2016-01-20 17:53
Potentially a duplicate of this: https://github.com/ractivejs/ractive/issues/2328

> @martypdx 
> Computed properties are as part of data initialization which happens prior to virtual dom creation or rendering, so there are no components to find.

Why not define age in the parent and pass it down to the child? https://jsfiddle.net/umtuw00e/1/

**Comment by magicdawn** [comment] 2016-01-21 03:34
@fskreuz 
Yeah. Actually Child's data are passed by Parent Component. I know this.
Here is my situation:

1. I have some useful method defined in Child Component, I want to call those method in the Parent Component, in computed property or somewhere. I will code like this https://jsfiddle.net/magicdawn/umtuw00e/4/ .
But it's not working so I need to implement those method again in the Parent like https://jsfiddle.net/magicdawn/umtuw00e/5/

**Comment by evs-chris** [comment] 2016-11-14 06:40
This goes against the typical flow of data, but it _is_ possible in 0.8 if you trigger an update on the `subAge` property once the main instance is rendered: https://jsfiddle.net/umtuw00e/6/

**Closed by evs-chris** 2016-11-14 06:40 UTC
Labels: question
