### ISSUE TITLE
Problem with ternary conditions

### ISSUE THREAD

**Issue by EduardJS** [ractivejs/ractive#2541] opened 2016-05-15 15:22 UTC
**Description of the bug:**
Ternary operators do not work, operations like `Math.max( 1, notifications[ this ].length )` always returns 1, it does not update.

**Versions affected:**
I have the latest commit from the edge version.

**Reproduction:**
http://app.mobilselskapet.no/ , open the console and type:
`content.fire( 'pushNotification', 'products', {}`

Look at the item in the navigation bar ( there will be a red circle with the number of "news" in that tab ).

**Code:**
```
<ul class="nav navbar-nav">
	{{ # tabs:i }}
		<li class="{{ activeTab == this ? 'active' : '' }}" on-tap="changeTab:{{ this }}">
			<a>
				{{ lang[ this ] }}
				<span class="navbar-new animated {{ notifications[ this ].length ? 'bounceIn' : 'bounceOut' }}">{{ Math.max( 1, notifications[ this ].length ) }}</span>
			</a>
		</li>
	{{ / }}
</ul>
```

If change it back to 0.7.3 ( latest stable ), everything works fine. You can look at my code and the templates. Maybe I'm doing wrong but I can guess something is shady with the latest build. Or did I miss any changelogs ?

**Comment by EduardJS** [comment] 2016-05-18 13:09
@martypdx Hello ! Do you know what this is related to ? Can I help you with any more info ?

**Comment by evs-chris** [comment] 2016-06-11 02:21
@EduardJS I was looking into this, and it would help tremendously if you could create a [fiddle](http://jsfiddle.net) or codepen or something like that reproducing the problem. It looks like you may have changed your approach since you filed the issue originally, so I can't really tell what some of the original template was doing.

**Comment by EduardJS** [comment] 2016-06-11 13:37
Hei! Thanks for looking into it. I don't have that code anymore since it was not working. I'll try recreating the problem on jsfiddle and come back with a link in a few.

**Comment by EduardJS** [comment] 2016-06-11 13:53
@evs-chris Ok, found out the problem. It lies when using `Math.max` in my case, as it is not able to compute `notifications[ this ]` anymore. I have tried changing this to `tabs[i]` , maybe `Math` would apply it's own `this` context, but problem seems to persist.

[https://jsfiddle.net/x64pm74g/1/](https://jsfiddle.net/x64pm74g/1/)

The ractiveJS external resource is the latest commit, from my server, served via HTTPS as JSFiddle does not allow me anymore to import resources on HTTP protocol ( and the ractivejs.org cdn does not have a valid certificate anyway ).

If I use 0.7.3, it can compute `notications[ this ]` into `Math.max` while `0.8.x` cannot.

`Ractive.js: Failed to compute @Math\.max(1,notifications[tabs\.2]\.length): Cannot read property 'length' of undefined`.

**Comment by evs-chris** [comment] 2016-06-13 05:43
Thanks for the report! It _was_ length changing from array modification when being referenced from a certain type of computation. It should be fixed in edge now :smile:

Rabbit trail, I'm not entirely sure why jsfiddle forces you to use https for new fiddles. There is a way to get a plain http fiddle, but it's not something a simple as just 'go to jsfiddle and type stuff in'. I'm not wild about codepen's interface, but it's growing on me, it has all of the features of jsfiddle, my designer buddies use it, and it doesn't force me through https all of the time. /rant

**Closed by evs-chris** 2016-06-13 05:43 UTC
Labels: bug
