### ISSUE TITLE
Animations on child elements behave... Interestingly

### ISSUE THREAD

**Issue by ISNIT0** [ractivejs/ractive#2097] opened 2015-09-01 14:48 UTC
http://jsbin.com/kigilocale/1/edit?html,js,output

The example is fairly self explanatory, nested elements with animations just duplicate when they should show/hide.

**Comment by heavyk** [comment] 2015-09-04 23:28
btw, this is working now. I remade that one as a fiddle, and it works properly on edge/latest

http://jsfiddle.net/jrrvahn4/

**Comment by ISNIT0** [comment] 2015-09-07 08:07
Hi @heavyk It seems you missed including the slide transition plugin: http://jsfiddle.net/jrrvahn4/2/

**Comment by heavyk** [comment] 2015-09-07 11:07
ah, you are correct!
never used a transition plugin before... gonna check them out

**Comment by ISNIT0** [comment] 2015-12-06 11:45
@heavyk Any thoughts?

**Comment by heavyk** [comment] 2015-12-07 12:40
ummm, obviously the problem is in the slide transition plugin, and not ractive?

I've still never used it so I can't help you much.

**Comment by fskreuz** [comment] 2015-12-07 13:25
[It's also broken in 0.6.x](http://jsfiddle.net/13ko3n2f/). However I don't think this is related to Ractive as removing the plugin [doesn't affect the rendering/unrendering of the section](http://jsfiddle.net/13ko3n2f/1/).

A really nifty way of doing this is to [just use CSS transitions, transitioning `max-height`](http://jsfiddle.net/13ko3n2f/2/). Saves JS from doing the logic and rendering.

**Comment by heavyk** [comment] 2015-12-07 19:55
that's a neat trick @fskreuz ... gonna use that :) cheers

**Comment by evs-chris** [comment] 2016-03-18 05:51
Was looking into this for some transition refactor fun, and it actually looks like the slide transition is just falling over when used with a span. If you change the span to a block (or at least a non-inline) element, it works just fine. I haven't gotten _too_ far into it, but it's looking like the slide is just not completing, in which case, Ractive should probably just have a forced completion/cancellation based on the duration supplied to keep stuff like this from happening.

**Comment by ISNIT0** [comment] 2016-08-15 08:10
This seems to be fixed on edge now, that due to your changes @evs-chris?

**Comment by evs-chris** [comment] 2016-08-15 17:44
Yes, we recently added forced completion to transitions so that if they don't complete after their duration, they are shut down by Ractive. I suppose it's safe to close this now :smile:

**Closed by evs-chris** 2016-08-15 17:44 UTC
Labels: bug
