### ISSUE TITLE
Ractive 0.8 - deleting item from inside a loop that includes conditional statement with reference, crashes

### ISSUE THREAD

**Issue by kouts** [ractivejs/ractive#2321] opened 2015-12-16 16:07 UTC
I'm sorry for the description, couldn't find a better way to describe it.
Here is the fiddle: http://jsfiddle.net/hhfpsm44/14/

You'll need the console open for this one.
Click on any of the delete buttons and you get:
Ractive.js: Failed to compute @(objects\.3\.characteristics\.indexOf(33051)>-1)?"":"inactive": Cannot read property 'indexOf' of undefined

On firefox you'll get a noticeable delay before the item gets deleted.

This works as expected with Ractive 0.73

**Comment by danjford** [comment] 2015-12-17 16:28
@kouts, I've just had a quick look and I think the problem is that you're doing an index of even when the item may not be defined. 

I've just added extra parts to your conditional statements so that it will check for the existence of the item before trying to perform an indexOf.

**Example**
```
{{ (characteristics && characteristics.indexOf(code) > -1) ? '' : 'inactive' }}
```

See my updated [jsfiddle](http://jsfiddle.net/hhfpsm44/15/).

**Comment by kouts** [comment] 2015-12-17 16:52
Ok thanks! But why does it work with Ractive 0.73?
Plus, "characteristics" is always defined in my example...

**Comment by martypdx** [comment] 2015-12-17 17:07
It's a bug because Ractive shouldn't be recalculating expressions in array members that have been removed.

**Comment by danjford** [comment] 2015-12-17 20:36
I've had this issue happen to me in a previous version. It may have been 0.7.3, it may have been under different circumstances though, I can't really remember.

**Comment by evs-chris** [comment] 2016-01-27 06:20
This is now fixed in edge.

**Closed by evs-chris** 2016-01-27 06:20 UTC
Labels: bug

**Comment by kouts** [comment] 2016-01-27 07:23
Thank you!
