### ISSUE TITLE
`onchange` triggered for root instance but not for components

### ISSUE THREAD

**Issue by dagnelies** [ractivejs/ractive#1990] opened 2015-06-11 14:52 UTC
Hi,

dunno if it's a bug or a feat, but `onchange` does not trigger for values mapped to a parent instance:

http://jsfiddle.net/o843futo/

it'd be nice to mention this in the docs or alter the behavior so that onchange is always called.

this is probably related to #1978

Cheers

**Comment by fskreuz** [comment] 2015-06-12 03:19
Definitely a bug. Here's a 0.6 fiddle http://jsfiddle.net/o843futo/1/ which works.

**Comment by martypdx** [comment] 2015-06-12 06:09
IMO it's a nofix by design. With the strong data ownership introduced in `0.7` `onchange` only fires for data owned by the instance. 

Observe works across all data accessible by the component. Is there a use for `change` beyond what observers can do?

**Comment by dagnelies** [comment] 2015-06-12 07:28
@martypdx Let's say it like this: it's very conter-intuitive.

If it's meant to be that way, all right, but it should at least be documented with a big warning. Otherwise, people will go nuts trying to understand why their onchange isn't triggered, like me. 

...but ideally, I'd call both, just for the sake of being what's natural/expected/intuitive.

**Comment by Madgvox** [comment] 2015-06-12 08:35
I have to agree that it is a bit counter-intuitive. It makes sense for a component to "own" any data that passes through it. It doesn't have to actually own the data, as per `0.7`, but it should at least know about it. Basically, if you're able to touch the data, it should be able to touch back.

**Comment by fskreuz** [comment] 2015-06-13 23:36
I agree with the rest. :+1:

**Comment by dagnelies** [comment] 2015-11-03 07:36
Really a pity this is closed.

From a design perspective, it's really nonsense. If a value of a component changes, it should trigger `onchange`. That's it. Not depending on who maybe has the ownership.

@martypdx mentioned:

> Observe works across all data accessible by the component.

What I also don't get is: if observers could catch all data, why couldn't `onchange` as well? Why do we differentiate a `observe('*',...)` and on `onchange`.

Btw, the `observe('*',...)` never worked for components anyway ( http://jsfiddle.net/mku42tuy/ )

**Comment by Madgvox** [comment] 2015-11-03 07:55
I closed this due to the lack of continued discussion and the `wontfix` tag. If there's still discussion to be had (and it appears there is!) then I will gladly reopen the thread.

**Comment by dagnelies** [comment] 2015-12-01 11:17
This is getting worse. Now an isolated component scope change gets triggered in the root scope instead!

**Comment by martypdx** [comment] 2015-12-13 18:14
@dagnelies take a look at #2319 which fixes all the issues with using observe in lieu of change events and let me know what you think.

**Comment by dagnelies** [comment] 2015-12-17 17:30
Hi,

basically, I'm very happy we can now observe all changes on a component. Whether it's one way or another.

However, I'm still disturbed by the asymetric behavior of `onchange` vs `observe`. In my simplistic view of the world, I thought that changes, once detected, would trigger the `onchange` event and if it matches some observer's pattern, trigger these as well. ...I mean, it's kind on the same. So I'm really puzzled that these two methods appear to be triggered from some totally unrelated parts.

As for the onchange as it is now, the current issue is that data local to a component triggers an "empty" onchange at the root instance. This is rather odd as well.

I'd still be very curious about how these `onchange` and observers are organized and what's the relationship between them.

And for now, I wish you nice festive days!

**Comment by fskreuz** [comment] 2016-01-03 23:04
Playing with events today and came across this owner-change situation. I'm curious on how Ractive determines the "owner" of the data. Might be a good thing to document.

**Comment by evs-chris** [comment] 2017-01-30 07:18
Recursive observers are now available on edge and can optionally include mapped data.

**Closed by evs-chris** 2017-01-30 07:18 UTC
Labels: observers, wontfix
