### ISSUE TITLE
guidelines for contributing questions

### ISSUE THREAD

**Issue by dagnelies** [ractivejs/ractive#2464] opened 2016-03-23 11:24 UTC
Hi,

first off, its appearance is brand new right? (or was I blind until now?)

I just checked the fiddle, and I was a bit confused.

* What are `<div id="qunit"></div>` and `<div id="qunit-fixture"></div>` there for?
* Shouldn't we put ractive's template in `script` tags somewhere?
* What are those options below the text exactly?

...it's fancy indeed. However, I really miss "seeing" the result/bug quite a lot! 
A fair share of bugs are also related to interacting with elements and visual glitches.

**Comment by fskreuz** [comment] 2016-03-23 12:12
Uhm... what fiddle?

**Comment by dagnelies** [comment] 2016-03-23 13:18
When you add a ticket, a red banner appears now, linking to:

https://github.com/ractivejs/ractive/blob/dev/CONTRIBUTING.md

and with the following fiddle:

http://jsfiddle.net/rich_harris/UG7Eq/

**Comment by fskreuz** [comment] 2016-03-23 13:38
Ohh, that fiddle.

1. The markup is taken from [the Qunit page the browser tests use](https://github.com/ractivejs/ractive/blob/dev/test/__support/index.html). The fiddle actually has a built-in QUnit set up. You can easily reproduce what you would normally see when running the unit tests on the browser.

    `<div id="qunit-fixture"></div>` is the test container. This is where instances get rendered for testing for those tests that need the instance rendered.

2. You _could_. But in the unit tests in the repo, you don't have an HTML page to work with. Each test is inside a JavaScript file so you're left with strings. I personally prefer template strings to construct templates because they can multi-line.

3. If you mean this:
    ```js
    t.equal( fixture.innerHTML, 'hello world!' );
    t.deepEqual( ractive.get(), { name: 'world' });
    ```

That's a sample test. It just tests if the component rendered "hello world" and if the data is `{ name: 'world' }`

If it all runs fine, you should see something like:

![screen shot 2016-03-23 at 9 32 05 am](https://cloud.githubusercontent.com/assets/1582932/13986703/3d15427c-f0da-11e5-81d2-fddab82ea964.png)

**Comment by Rich-Harris** [comment] 2016-04-02 21:36
Closing as no action required

**Closed by Rich-Harris** 2016-04-02 21:36 UTC
Labels: question
