### ISSUE TITLE
ractive.js:8606 Uncaught TypeError: c.reset is not a function

### ISSUE THREAD

**Issue by ghost** [ractivejs/ractive#2782] opened 2016-11-25 12:03 UTC
**Env:** Node
**Version:** Ractive 0.8.2 edge
**Fiddle:** https://jsfiddle.net/phrearch/ngt9dbv0/2/

I made a fiddle but the error only occurs in Nodejs(using Ractive for SSR with _this.renderer.toHTML()_):

```
Unhandled rejection TypeError: c.reset is not a function
    at /home/spindle/projects/garage11/garage11/node_modules/ractive/ractive.js:8607:30
    at Array.filter (native)
    at Object.reset (/home/spindle/projects/garage11/garage11/node_modules/ractive/ractive.js:8605:18)
    at Child.Ractive$reset [as reset] (/home/spindle/projects/garage11/garage11/node_modules/ractive/ractive.js:8706:25)
    at Child.observe.init (/home/spindle/projects/garage11/garage11/apps/vdom/components/app.js:26:30)
    at Observer.dispatch (/home/spindle/projects/garage11/garage11/node_modules/ractive/ractive.js:4142:19)
    at dispatch (/home/spindle/projects/garage11/garage11/node_modules/ractive/ractive.js:1263:13)
    at Array.forEach (native)
    at flushChanges (/home/spindle/projects/garage11/garage11/node_modules/ractive/ractive.js:1269:10)
    at Object.end (/home/spindle/projects/garage11/garage11/node_modules/ractive/ractive.js:1202:5)
    at set (/home/spindle/projects/garage11/garage11/node_modules/ractive/ractive.js:1382:12)
    at Child.Ractive$set [as set] (/home/spindle/projects/garage11/garage11/node_modules/ractive/ractive.js:16587:11)
    at VDom.set (/home/spindle/projects/garage11/garage11/lib/vdom.js:79:17)
    at Promise.all.then (/home/spindle/projects/garage11/garage11/apps/settings/modelview.js:77:43)
From previous event:
    at SettingsApp.updateContext (/home/spindle/projects/garage11/garage11/apps/settings/modelview.js:57:10)
    at peer.router.route (/home/spindle/projects/garage11/garage11/apps/settings/modelview.js:26:18)
    at next (/home/spindle/projects/garage11/lib11/lib/router.js:151:26)
    at Router.executeRoute (/home/spindle/projects/garage11/lib11/lib/router.js:154:11)
    at Router.dispatch (/home/spindle/projects/garage11/lib11/lib/router.js:181:22)
    at connect.connect.use.use.use (/home/spindle/projects/garage11/lib11/index.js:133:36)
    at call (/home/spindle/projects/garage11/lib11/node_modules/connect/index.js:239:7)
    at next (/home/spindle/projects/garage11/lib11/node_modules/connect/index.js:183:5)
    at next (/home/spindle/projects/garage11/lib11/node_modules/connect/index.js:161:14)
    at favicon (/home/spindle/projects/garage11/lib11/node_modules/serve-favicon/index.js:72:7)
    at call (/home/spindle/projects/garage11/lib11/node_modules/connect/index.js:239:7)
    at next (/home/spindle/projects/garage11/lib11/node_modules/connect/index.js:183:5)
    at Function.handle (/home/spindle/projects/garage11/lib11/node_modules/connect/index.js:186:3)
    at Server.app (/home/spindle/projects/garage11/lib11/node_modules/connect/index.js:51:37)
    at emitTwo (events.js:106:13)
    at Server.emit (events.js:191:7)
    at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:547:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
```

I checked ractive.js at line 8606 to see what `c` is. It returns the string `el` in that case. As a workaround I changed one line in ractive.js:

```
return order.filter( function ( c ) {
// If it's a string, then do nothing.
if (typeof(c) !== 'string')
    return c.reset && c.reset( ractive );
}).map( function ( c ) { return c.name; } );
```
The error is gone now and the `appname` change seems to be properly propagated through the vdom, as the right dynamic component is returned. Not sure why this happens.

**Comment by paulocoghi** [comment] 2016-11-25 17:13
Can you try with latest version in 0.8 branch? (0.8.5)
https://unpkg.com/ractive

**Comment by ghost** [comment] 2016-11-25 18:00
Hmm... I can't seem to reproduce. I'm probably missing something here 🤔 . It's also hard to tell from code since strings don't have a `reset` method at all, and registries, template and css configurators either have a reset property which is a function or none at all. Both cases should be captured by the existing `c.reset && c.reset( ractive );`.

```js
const order = [].concat(
	defaultKeys.filter( key => !registries[ key ] && !custom[ key ] ), // has no reset
	registries, // has resets
	custom.template, // has reset
	custom.css // has no reset
);
```

Can you provide a minimal version of this script that I can run through Node directly to reproduce the issue?

Also, do you happen to use libraries that modify prototype properties (i.e. augments `String.prototype` and/or `Object.prototype`)?

**Comment by evs-chris** [comment] 2016-11-25 18:08
I don't have a proper machine to look at it right now, but it's probably being caused by the `el` property not being replaced by a proper element since it's never being rendered to DOM.

**Comment by evs-chris** [comment] 2016-11-26 03:37
Yep, I'm not sure where this is coming from either, unless there's something playing with a prototype like @fskreuz said. We _can_ change it to `typeof c.reset === 'function' && c.reset( ractive )`, but there's definitely something strange about whatever is happening to your `el`.

**Comment by evs-chris** [comment] 2017-01-14 04:08
I'm going to go ahead and close this, but if we need to follow up further, please feel free to reopen it.

**Closed as completed by evs-chris** 2017-01-14 04:08 UTC
Labels: inquiry/pending clarification
