### ISSUE TITLE
npm and browser version templates mismatched for ractive 0.6.1 (in edge)

### ISSUE THREAD

**Issue by kurdin** [ractivejs/ractive#1672] opened 2015-01-30 20:43 UTC
``npm install ractive`` and ``wget http://cdn.ractivejs.org/edge/ractive.js`` has same version number ``0.6.1`` but code is different and templates version number mismatched. 

This lead to the issue with compiled template on server can not be used in browsers.

Hmm. I just found that edge version is changed, so maybe this is not valid issue. 

Anyway, it would be nice to do ```npm install ractive@edge``` as well (maybe).

**Comment by codler** [comment] 2015-02-01 09:05
You can use `http://cdn.ractivejs.org/latest/ractive.js` instead

**Comment by Rich-Harris** [comment] 2015-02-02 00:06
This came up the other day in #1632 - `npm install ractive@edge` won't work (because you can't overwrite versions on npm, so no moving targets like `edge`), but `npm install ractivejs/ractive#build` does (it just points at the [build branch](https://github.com/ractivejs/ractive/tree/build), which Travis updates on each successful push).

Related: I've opened #1677 to bump the edge version to 0.7.0-edge, as it should be.

The template mismatch thing is a colossal nuisance... best solution is for us to get 0.7.0 out the door!

**Comment by Rich-Harris** [comment] 2015-03-18 03:19
0.7.x is finally out, so I'll close this issue

**Closed by Rich-Harris** 2015-03-18 03:19 UTC
Labels: bug

**Comment by krasimir** [comment] 2015-03-18 10:43
@Rich-Harris thanks for releasing 0.7 version. However, we still got the error above. We are pulling the client-side version from here http://cdn.ractivejs.org/latest/ractive.js The version right now is 0.7.1 and that's the same version that we install via npm. So at the end we have same 0.7.1 in the browser and in our gulp setup. I still see 
![image](https://cloud.githubusercontent.com/assets/528677/6707096/5413df0c-cd6c-11e4-96cb-96f96c1999e7.png) in the console.

**Comment by Madgvox** [comment] 2015-03-18 10:51
What specifically are you using to parse your templates? I've run into this before when using another package ([ractive-loader](https://github.com/rstacruz/ractive-loader)) to parse my templates because it was using a very old version of ractive.

**Comment by krasimir** [comment] 2015-03-18 11:00
@Madgvox we are using this package https://www.npmjs.com/package/ractive and as far as I can see it is the official one.

**Comment by krasimir** [comment] 2015-03-18 11:04
As a temporary solution I'm using that build http://cdn.ractivejs.org/releases/0.6.1/ractive.min.js and 0.6.1 version of the npm package.

**Comment by Madgvox** [comment] 2015-03-18 11:09
Yes, that is the correct package.

Can you verify that the TEMPLATE_VERSION is being defined correctly in both http://cdn.ractivejs.org/edge/ractive.js and your npm file? 

It should defined be around line 15 and the line should equal `var TEMPLATE_VERSION = 3;`.

**Comment by krasimir** [comment] 2015-03-18 11:16
I'll check that later today. (in a rush to release on production with that 0.6.1 version)

**Comment by krasimir** [comment] 2015-03-18 11:16
Thanks for the quick response btw :)

**Comment by krasimir** [comment] 2015-03-18 12:10
@Madgvox yep, they both have `TEMPLATE_VERSION = 3`

![image](https://cloud.githubusercontent.com/assets/528677/6708380/5e99598c-cd78-11e4-8b40-32eccedabf22.png)

![image](https://cloud.githubusercontent.com/assets/528677/6708388/67f3b4be-cd78-11e4-9d3a-564551222205.png)

**Comment by martypdx** [comment] 2015-03-18 12:41
@krasimir but how are you packaging and loading your templates?

**Comment by krasimir** [comment] 2015-03-18 12:45
Here is the gulp task that I'm using:
```js
gulp.task('templates', function() {
  return gulp.src('./templates' + '/**/*.html')
  .pipe(tap(function(file, t) {
  	var p = path.normalize(file.path).replace(__dirname, '');
  	if(p.charAt(0) === '/') p = p.substr(1, p.length);
    var code = 'templates[\'' + p + '\'] = ';
    file.contents = new Buffer(code + JSON.stringify(Ractive.parse(file.contents.toString())));
	}))
  .pipe(concat('templates.js'))
	.pipe(wrap('module.exports = function(key) { var templates = {}; <%= contents %>; return templates[key]; }'))
  .pipe(gulp.dest('./build'));
});
```
It basically converts the following:
```html
<span class="{{cssClass}}">{{data}}</span>
```
to
```js
// in build.js
...
templates['<path-to-template here>'] = {"v":1,"t":[{"t":7,"e":"span","a":{"class":[{"t":2,"r":"cssClass"}]},"f":[{"t":2,"r":"data"}]}]}
...
```

**Comment by martypdx** [comment] 2015-03-18 13:42
From this: `{"v":1,"t":[{...` you can see it's producing version 1 of the template spec. Can you check the Ractive version the gulp task? You can do this by adding:

```js
var Ractive = require('ractive');
console.log(Ractive.VERSION);
gulp.task('templates', function() {
...
```

**Comment by krasimir** [comment] 2015-03-18 14:42
It's 0.7.1
![image](https://cloud.githubusercontent.com/assets/528677/6711129/c985b622-cd8d-11e4-8e5f-7315d04a9f02.png)

**Comment by martypdx** [comment] 2015-03-18 15:10
[This](http://jsfiddle.net/of6swhb9/) indicates that the right template version is being created.

Next question, is there any chance that because source template files haven't changed that gulp is not actually regenerating new versions of the file?

**Comment by krasimir** [comment] 2015-03-18 15:36
@martypdx that was the problem. I deleted the compiled file and forced gulp to recreate it. This time I see `"v": 3`. I'm glad that the problem is not in the framework. Thanks!
