### ISSUE TITLE
Help: Memory issue in IE11

### ISSUE THREAD

**Issue by 4lbertoG** [ractivejs/ractive#2290] opened 2015-11-27 10:33 UTC
Hi:
We have an application with ractive and we are experiencing problems with memory consumption, mainly with IE11. When a component is accessed IE11 goes up to 1gb of ram. This component have a great amount of data, but the problem is, when you navigate to other component, memory is not released. We have tried to force the memory release within the “onteardown” method, but it’s not working. In IE10, Chrome and firefox the memory management is better, but it also increases.

Our application uses require, jquery, Ractive, rvc, Backbone, backbone-deep-model, underscore and D3 for graphics. 

We tested some solutions but none seem to work. Any advice or help on freeing memory will be very useful.

**Comment by fskreuz** [comment] 2015-11-27 11:38
Can we see a demo, profiler output or the component source itself? Also, which version do you use? You've got a lot of moving parts there, we're not sure what's causing the memory hogging.

**Comment by 4lbertoG** [comment] 2015-11-27 13:55
Thanks for responding. Ractive version is 0.7.3, backbone v 1.1.2. As would be difficult to summarize, I put some code. I know the js is a mess and needs some refactor, separate 'onrender' and 'oninit', etc... but its my first spa in ractive. But beyond that, we cant clean memory in IE11,

The entry point is app.js (appjs.pdf), the controller ventaaecoc.js and the component ventasaecoc.html. We have tried to clear memory on the method 'onteardown' but it didnt work. 

[appjs.pdf](https://github.com/ractivejs/ractive/files/45765/appjs.pdf)
[ventaAecochtml.pdf](https://github.com/ractivejs/ractive/files/45767/ventaAecochtml.pdf)
[ventaaecocjs.pdf](https://github.com/ractivejs/ractive/files/45766/ventaaecocjs.pdf)

Thanks.

**Comment by Rich-Harris** [comment] 2015-12-05 22:24
PDFs?! :grimacing: It's going to be difficult for anyone to help you based on these – any way you can create a repo with as much code as is necessary to reproduce the issue? Impossible to figure out what's going on without a running version of the app.

**Comment by martypdx** [comment] 2015-12-05 22:53
Does IE11 tell you _what_ the objects are that are holding onto memory (like chrome does)?

**Comment by 4lbertoG** [comment] 2015-12-09 09:06
Yep. I know pdfs is not the best...but i cant put a working version of the app, there are private data. I tried to make a snapshot in IE11 but the browser runs out of memory. I'll try to isolate the component and load a json with mock data and put the code and a snapshot here. Thanks all!

**Comment by evs-chris** [comment] 2016-10-23 08:01
I'm going to close this due to its age. Note that giving a large tree of data to Ractive and then removing it later won't necessarily free up the model tree that Ractive allocates. This is one of those places where an unset or a gc may come in handy. In the js framework benchmark that went around not too long ago, Ractive trails in memory use because it creates 10,000+ objects in a list, which creates a model tree with 10,000+ models in Ractive. Those models don't go away when the list shrinks to 100 models.

**Closed by evs-chris** 2016-10-23 08:01 UTC
Labels: pending-clarification
