### ISSUE TITLE
Regression when removing array items with their own observers

### ISSUE THREAD

**Issue by ADantes** [ractivejs/ractive#2726] opened 2016-10-28 20:52 UTC
## Description:

When objects are removed from the view, this triggers observers that may modify/re-add said object to the view.  Rendering doesn't react well to the resulting state.
## Versions affected:

0.8.0, 0.8.1, 0.8.2
## Reproduce

Clicking "Remove" in the 0.7.3 version works as I intended.  Clicking "Remove" in 0.8.2 results in the filter controls not being removed _and_ the "No Filters" message being displayed.

0.8.2: https://jsfiddle.net/wztbsk1q/5/
0.7.3: https://jsfiddle.net/wztbsk1q/2/
### HTML

```
<script id="component" type="ractive/template">
  {{#filter}}
    <p>
      <select value="{{.category}}">
        <option>A</option>
        <option>B</option>
      </select>

      -&gt;

      <select value="{{.subcategory}}">
        <option></option>
        <option>I</option>
        <option>II</option>
      </select>
    </p>
  {{/filter}}
</script>

<script id="template" type="ractive/template">
  {{#each filters}}
    <Component filter="{{this}}" />
    <button type="button" on-click="splice('filters', @index, 1)">
      Remove
    </button>
  {{/each}}

  {{#if !filters.length}}
    No Filters
  {{/if}}
</script>

<main></main>
```
### JS

```
var Component = Ractive.extend({
  oninit: function() {
    this.observe("filter.category", function(category) {
      this.set("filter.subcategory", "");
    });
  },
  template: "#component"
});

new Ractive({
  components: {
    Component: Component
  },
  data: function() {
    return {
      filters: [{
        category: "A",
        subcategory: ""
      }]
    }
  },
  el: "main",
  template: "#template"
});
```

**Comment by evs-chris** [comment] 2016-10-28 21:20
I think this may be a regression of not-very-well-defined behavior prior to 0.8. What's happening is the component is being removed, which _does_ tear down the observer. But the observer is immediate, which means that it fires before DOM changes, like removing the component, happen. Setting the observer to `{ defer: true }` to give the component a chance to tear itself and its observers down first is one solution. Checking to see if the new value is `undefined` would be another.

The filter getting recreated while 'No filters' shows is due to a race condition while propagating the change to the mapping and deps. Observers that modify the observed keypath are a bit of a mine field.

**Comment by evs-chris** [comment] 2016-11-16 21:26
I think this is more a bug on the 0.7 side, which should also have required the observer to be deferred to not do weird things. I'm going to go ahead and close this, as there's not really anything that can be done about it beyond using a deferred observer. If those workarounds aren't acceptable, please feel free to reopen this.

**Closed by evs-chris** 2016-11-16 21:26 UTC
Labels: observers, regression bug
