### ISSUE TITLE
Question on updating view from a list

### ISSUE THREAD

**Issue by chuan137** [ractivejs/ractive#980] opened 2014-07-14 21:09 UTC
I am new to Ractive and it is my first time to ask question here. Please correct me if I am asking question at the wrong place.

It is a basic question about rendering data. I store some data in a long item list, which is rendered in a component. Data in item list are updated regularly, my question is how to make the view render on changes of data automatically?

```javascript
var citylist=[
           {name: 'Rome', x: 0, y:0},
           {name: 'Berlin', x:1, y: 20},
           {name: 'London', x:2, y:15},
           ...
]

r = new CityView({
      data: {
          cities: [ citylist[1], citylist[2], citylist[5], citylist[99] ]
      }
})
```

It seems to me, ractivejs build the keypath for r.data.cites and watch them. It will be nice the citylist itself is watched, then real time updating data on web page is much easier and flexible.

Does the idea make sense, or maybe I have not yet grasped the idea of ractivejs yet.

**Comment by evs-chris** [comment] 2015-10-23 07:43
Looks like there have been several improvements to array handling since this was opened. I'm going to close it, but feel free to re-open if the issue isn't resolved.

**Closed by evs-chris** 2015-10-23 07:43 UTC
