### ISSUE TITLE
Ractive Promise Error Handling

### ISSUE THREAD

**Issue by timoxley** [ractivejs/ractive#1788] opened 2015-03-10 20:18 UTC
Chrome does a godawful job of rendering errors (note stack trace not visible)
![image](https://cloud.githubusercontent.com/assets/43438/6583799/93248b54-c7a1-11e4-8969-71c29ef67fdf.png)

You can improve things with `console.error(err.stack)`, but this isn't standard.
![image](https://cloud.githubusercontent.com/assets/43438/6583831/c819aaec-c7a1-11e4-9e4c-5d0c723308e9.png)

This sucks but most problematic about the current state of ractive error handling is the debugger is mostly useless (even with the `async` flag on, that feature apparently not perfect).

After removing all of ractive's promise error handling code: `%s/.then(null, consoleError)//gc `, now Chrome will handle unhandled promise rejections pretty much as if they were thrown exceptions:

![image](https://cloud.githubusercontent.com/assets/43438/6583907/49cfba86-c7a2-11e4-9046-998f0c2e5365.png)

if dev tools is open it will even pause on the correct line.

![image](https://cloud.githubusercontent.com/assets/43438/6583880/29b5f030-c7a2-11e4-9bb4-072e0c102144.png)

Prior to a very recent of Chrome this was not the case and you certainly needed to have some kind of manual catch-all. 

Suggest adding a flag to disable these. Ideally this is outside the promise flow so it doesn't mess with stack traces.

**Comment by martypdx** [comment] 2015-03-10 20:29
Thanks for the info @timoxley, we put those in because error was being completely swallowed. Since then we've also we fixed the fact that the native `Promise` implementation was not being used. 

Perhaps we should use the `.then(null, consoleError)` when we're not using the native Promise.

**Comment by timoxley** [comment] 2015-03-10 21:08
> we put those in because error was being completely swallowed.

Yeah I recently had a 2 day long wild goose chase trying to figure one of those out. Absolute horror. Very relieved when Chrome added logging.

> Perhaps we should use the .then(null, consoleError) when we're not using the native Promise.

Yes this would be great, though even in that scenario it'd be nice if there was an option to let it throw instead of logging e.g. dev mode

**Comment by martypdx** [comment] 2015-03-10 21:21
> Yes this would be great, though even in that scenario it'd be nice if there was an option to let it throw instead of logging e.g. dev mode

But without the Chrome intercept of a native promise, isn't the issue that our own-rolled Promises call `then` async from the `setTimeout` ethers, and so throwing went up the stack to where all the lost socks from dryer go, never to be heard from again.

**Comment by Rich-Harris** [comment] 2015-03-14 03:26
On reflection there's basically only one reason to try and deal with these errors internally, and that's when the developer never gets hold of the promise inside which the error occurs. This is the case if a Ractive instance is automatically rendered (i.e. the `el` property is passed to `new Ractive()`, so the developer never calls `ractive.render()`).

Even though Chrome logs those errors now (praise be!), I think it's still probably worth doing our own thing, but only in that case. So my suggestion:

* Remove all existing promise-error-handling code
* Catch errors arising from an **automatic** render, and log them (for browsers that haven't caught up to Chrome), but then rethrow them.

Does that sound like it makes sense? Developers would be responsible for `.catch()`ing errors that arise inside a manual `render()` or `animate()`, but that's basically it (by design, other promise-returning methods do the bulk of their work synchronously outside of the promise callback, so we don't encounter this problem in too many places).

**Comment by Rich-Harris** [comment] 2015-03-14 14:07
I've raised a PR for the changes described above - #1815. Let me know what you think

**Comment by Rich-Harris** [comment] 2015-03-16 19:21
fixed in #1815

**Closed by Rich-Harris** 2015-03-16 19:21 UTC

**Comment by timoxley** [comment] 2015-03-17 01:31
:+1: LGTM
