### ISSUE TITLE
observe("*", ...) doesn't work inside components

### ISSUE THREAD

**Issue by dagnelies** [ractivejs/ractive#1988] opened 2015-06-09 09:29 UTC
Hi,

Here is the fiddle with `observe("*", ...)`:

http://jsfiddle.net/mku42tuy/

And here is the fiddle with `observe("value", ...)`:

http://jsfiddle.net/mku42tuy/2/

it results in the same for both latest and edge.

**Comment by frenchroasted** [comment] 2015-06-09 12:44
Looks like this is the same bug as issue #1978.

**Comment by Madgvox** [comment] 2015-06-09 21:46
Ah, thanks @frenchroasted! I knew I had seen this bug before, but I couldn't find the issue.

Apologies @dagnelies, I'm going to close this since it is a duplicate of #1978. If you have any more information about this bug, please feel free to post it in the previous thread.

**Closed by Madgvox** 2015-06-09 21:46 UTC

**Comment by dagnelies** [comment] 2015-06-10 06:36
Hi,
Sorry, I didn't noticed the other one.
Perhaps this example is a bit simpler though and could help nevertheless.

**Comment by Madgvox** [comment] 2015-06-10 06:53
Of course! I'll cross post your examples over to the other thread. I should have done that in the first place.

**Comment by dagnelies** [comment] 2015-10-15 14:58
@Madgvox
Hi, this bug has been marked as duplicate, and both are closed, yet the issue is still there.

**Comment by Madgvox** [comment] 2015-10-15 21:49
@dagnelies I could've sworn they were working last night when I checked them against edge! My mistake. I'll reopen that issue.

**Comment by dagnelies** [comment] 2015-10-16 07:42
thanks
