### ISSUE TITLE
writing in ES6 style code

### ISSUE THREAD

**Issue by devmondo** [ractivejs/ractive#1898] opened 2015-04-02 16:31 UTC
hi, this is amazing library, could you please help on this 

i am using jspm and writing code in ES6 Style and using the standard import syntax, so how we can change this
```
var ractive = new Ractive({
  el: 'container',
  template: '<p>{{greeting}}, {{recipient}}!</p>',
  data: { greeting: 'Hello', recipient: 'world' }
});
```

to this
```
export class Sample{
constructor(){
this.el='container';
this.template =  '<p>{{greeting}}, {{recipient}}!</p>';
this.data = { greeting: 'Hello', recipient: 'world' };
}
}
```

thanks in advanced.

**Comment by martypdx** [comment] 2015-04-02 18:32
Seems related to #1885, though to be honest I'm not sure where you're headed with that example.

Do you mean `export class Sample extends Ractive {`?

**Comment by devmondo** [comment] 2015-04-02 19:01
thanks for answering, yeah that is exactly where i am trying to go

**Comment by Rich-Harris** [comment] 2015-04-11 23:15
Right now I'm afraid that's not really possible, because of the reasons outlined on #1885 (basically, `extends` just sets up a prototype chain, whereas `Ractive.extend(...)` does some one-off setup work and merges a bunch of objects). It's something we might look into in future - at the moment, it would involve a ton of breaking changes, and it's not quite clear what the benefit would be apart from a slightly nicer syntax.

I'll close this, as it's effectively a dupe of #1885.

**Closed by Rich-Harris** 2015-04-11 23:15 UTC
