### ISSUE TITLE
is there no replacement for magic:true for externally changing data-array?

### ISSUE THREAD

**Issue by wgrhstf** [ractivejs/ractive#3270] opened 2018-10-02 06:02 UTC
## Description:
Since the magic Parameter has been removed I cannot find a sufficient method to replace it. My whole application is built on  a PouchDB and I showed the constantly changing data without reloads. With `magic: true` all the changes where shown automatically and smoothly animated. But using `.update()` triggers my whole ractive to be redrawn which looks horrible. 

## Versions affected:
from 0.9 onwards

## Reproduction:
My Code in a very simplified form:
```

fetchInitialDocs().then(renderDocsSomehow).then(changesIncoming).catch(console.log.bind(console));

function fetchInitialDocs(){
   //=> get the Data from PouchDB and build my Array
}

function renderDocsSomehow() {
    let myRactive = new Ractive({
      el: '#myDiv',
      template: 'my Template',
      data:{
        doc1: docs // => this is the Array all the Data is stored into
      },
      components: {myComponents},
      computed: {computedValues}
    });
    return myRactive;
}
function changesIncoming() {
    //here my changes appear
    renderDocsSomehow().update() 
}
```
This works, but in my Interface there are a lot of foldouts, accordions and chart.js graphics, and all of those are reset or redrawn every time an update comes in (which can happen a couple of times every second). Is there a better way to replace the `magic: true`?

**Comment by dagnelies** [comment] 2018-10-02 08:47
I believe `magic: true` was deprecated/removed in last version. Mainly because of various bugs and code complexity if I remember right.

...I guess the best option is to use `ractive.set(....)` when your data comes in. There are a couple of options you might try out to improve rendering. See https://ractive.js.org/api/#ractiveset

**Comment by wgrhstf** [comment] 2018-10-02 12:00
Yes it was, and though I do understand why it was removed I cannot find any workaround. 
If I use  `set(docs[index])` I get the same result as with `.update()`:  the whole template get's redrawn and not only the changed item animated to it's new value as it was with `magic`.

**Comment by dagnelies** [comment] 2018-10-02 12:27
What about `set(docs[index], {keep:true})`? ...or a `set(docs[index], {deep:true})`? (the latter one requires setting children elements to `null` to delete them). That should reduce re-renderings.

**Comment by ghost** [comment] 2018-10-02 12:28
The theory was to move this functionality into an [adaptor](https://ractive.js.org/plugins/#adaptors) and have it work in the same way you sync Ractive POJO data with non-POJO data (e.g. Backbone models, RxJS observables, etc.). How exactly this should happen, I haven't wrapped my head around (yet)

**Comment by giovannipiller** [comment] 2018-10-02 12:33
Assuming the issue is caused by an ‘each’ statement, you could provide a keypath to the new ‘shuffle’ option:

https://ractive.js.org/api/#each-sections

**Comment by wgrhstf** [comment] 2018-10-02 13:09
The `deep`and `keep` had no Effect on the behaviour, but as for the `each` I really do use that quite excessively in my template. But `ractive.set(docs[index], {shuffle :true});` did nothing (but I must admit even though I read the docs I did not fully understand how shuffle works)

**Comment by giovannipiller** [comment] 2018-10-02 13:20
> {{#each people, 'profile.id' as shuffle}}...each person's profile id determines where they are in the list...{{/each}}

If I remember correctly, assume some data like this:

```javascript
...
data: {
  people : [
    { profile: { id: 1 } },
    { profile: { id: 2 } },
  ]
}
...
```

Having this in the template:
```
{{#each people, 'profile.id' as shuffle}}
  <div slide-in-out>...</div>
{{/each}}
```

Items whose 'profile.id' is already rendered, won't be removed/added.

Ex. Replacing `people` with:

```javascript
this.set('people', [
  { profile: { id: 1 } },
  { profile: { id: 3 } },
]);
```

will:
- keep the `<div>` for profile.id = 1 as it is
- transition **out** the `<div>` for profile.id = 2
- transition **in** the `<div>` for profile.id = 3

**Comment by wgrhstf** [comment] 2018-10-02 13:48
Ok that sounds logical. thanks for the explanation. 
I'll try to build it that way, but I'm not sure if that works in my case. All the arrays I use in my template are computed values, and quite complex in their structure. If I have to address every value in each `{{#each}}` separately as shuffle this is going to end up really complicated. 
Despite the fact that it made problems or was not considered best practice, that's what I really liked about the `magic: true`. You had not to address every change manually and could concentrate on other stuff while ractive took care of the data updates.

Edit: No change in behaviour. I tried `shuffle` and also `animate()` but it always renders the complete ractive, not only the changed data. Guess I'll stick to Version 0.8 till I find a solution...

**Comment by evs-chris** [comment] 2018-10-02 19:37
Can you put together a minimal-ish example that displays the undesired behavior? If I have something I can play with, I may be able to come up with a solution for a `set` option, but I'm not positive I'm understanding the situation fully. Something in the [playground](https://ractive.js.org/playground) would be great, but a repo or fiddle would work too.

**Comment by wgrhstf** [comment] 2018-10-03 06:52
I've set up script at Playground that shows what I'm am trying. It's not exactly what my original script does because I could not use all of the features, but has the same Problem and uses a similar approach. Feel free to have a look [here](https://ractive.js.org/playground/#N4IgLiBcIDwDYEsB2BrABAJwKZwLwB0QBnMATziyIAsssxC0rsAzAkAenaToBMkBDAHQAjAPaiwJDPwAOAYz6C5ogLbsxEqbPYBmQQAZBO9nKJF14yWGkzBK5ErOEAfPiQwicjAhlg0RDDk2KjAwGSJITgUkACsiJThRAFceZjh+bCVVdn4Y-gAPdkRhcxiARySsDFJdI0EARnZyyurBOJcYdk9vX1d3bp8-AKDCTm4wPiENKxtorLVprRlaw2M4i01rWTsHdpBnToHetxgeBAA3NAQeNgAZBBJkAHMO9jPzvphhJNDRJDQ-nJEHIUGw5FR+EgnpQAJJIZT2KEACgAlABuFzgyHQtAAd2QPFEuKInW+vyQzhAABpiFAQGg0BQ-ITTGhcGgANrANwMhkAfWukDQhAATCKACz6EVYAAcOgAtDK5PUFeKdMIAGzy-gimUAVnlIrkMqwAE4dPUsAB2fjCGWEKk83kAJXEKgEKiwQsIABVKNY3Q6nQzRDIsEgAOoEokRTnB4VgYD4pCE-E8b0geoinTiwgAX0d-15DKT0bTGez4r1+cLxZLydTguFID1eo1Gpr8YAurXeQ2Y0Lq0WC8ABenm2LJdK5Yrlar1VqdfrDcazVXrRgwLnqfHXaoPV7m36pG60CKg0WQ2HI2XYxz4-hE-3y82qzpzyAC-H62Wm6KRfU9T5t2vYMs+sb2sO35oF2GJIG42AplUAAioimKicHMEk8JgAgfyYOGPAoWhRComg3JFsoSAkGgADKYD8JIbJoAA5KcFzOMAwAAMT3CQeZ5ixADU0EMmx7xoEC-BmGwMiQjg8pPBgyQyB0ElSTJhBydwcBoNpClEcw-BJHA9D7OxlwaUQsnyXA8o0PwZxQi4wnxmxVDipJ6SaSA+l2bhYAUB0-BoDwjH8PKYCiE8TwUGCohwOk4RYAwTBYKwhDcVxY4CS4XF7u6-CegJnT8Ac7AeeV7zOK5l51ixXHcQgzAAteUYpjGggUFCYBUGgzhoPoJXqd51lacpSmUEQakXF50ljb5E3YGY8rCBkelLVNq0ZPKRBJHIchTQwylxeN0XLUQa0YAwJDkFgbBpr1QpcaG4btam8TdU8vXsOBaAAFRoPU+j6GgAkAKR5cAACyjFUIIynYTwSKvTeHXEl14bfVQv23gDQMgyiYN5uDXmiEQWA8Gg70xp01UWXNPkyJtK1XRt51bVd8phVCVQ3WQp0gI9VCQFxwP6PKqM0xjX0-X9gPixDrz028HFcewzUCbVda8mxqsfNrOusQz1xsNl1y5fSVk2Tp8rKIlsgU5JCVJRTHQmZxPFS7eJWIJ7z4W3mnR++r3vo0QJXsB7ht69V6t8WAkfVSxcHFkyaAqKQzr8HIuHnFgzHcLiaDZ7nFxYEiFE6zgQosbxDy4VCLGgbyYBYCoMjpG3Qr0YxRAtwyYUMaLLIRwPzsdz8lPPaJaAJ2RVdGwy6dtx3iA0eyvUPII0JgEiLGjyx6Kzwy2BgEkGD-KvncN7PebQffdV5sfdVnxf-yZ6XedYHBj9YTheF-hYl5kQOECJngL3jJwGg2AM6kEkhCEBaBZBhgyE6UezEuTxjHBmZm8pDQSilLKBUSoVTyjVJqbUuoDRGhNOaS0No7QXmLAVA8GZjwBlUMw3kYcPpCnvHVR8pZ0Z-kzJWTsdUfwiPHKKHM1ZPwgXjOBQcToRw4ObHgghU5iGzjIRQxc1CVx0PXIw+0O46qsKKoeX0-plKqA-C3XhA44yCKfL+GRIA3wfi-JI8iAcPFikAhInWwjGwBIAt48eoSiSiMCToYJdZokvn-PUbcPjiw9iUbeIUkEGSPx1rBeMiEiIYFQuhFEggkgyCHhXF+eZqQgDkHSBpVAoCgAwHSeoBhPx5iAA).

**Comment by dagnelies** [comment] 2018-10-03 07:14
I don't see any rendering issues here. Moreover, you are re-creating a brand new Ractive instance each time you click on the button. Lastly, there is a useless `update()` call. I also advise moving the template itself inside a script instead of string concatenations, it'll be more readable. ...but mainly, I don't see any issues with the example.

**Comment by wgrhstf** [comment] 2018-10-03 07:28
You are absolutely right. I just did not realize that with every call of  `renderDocsSomehow()` I create I new Instance of myRactive... No wonder it get's redrawn.
If I define my Ractive at the very beginning of the script, so it is globally accessible I can use `.update()` and everything works great. 
Thanks a lot!

**Comment by ceremcem** [comment] 2018-10-03 07:38
I was about to say the same thing as @dagnelies did, but I also want to share a re-write according to my understanding: [Playground](https://ractive.js.org/playground/#N4IgLiBcIDwDYEsB2BrABAJwKZwLwB0QBnMATziyIAsssxC0rsAzAkAenaToBMkBDAHQAjAPaiwJDPwAOAYz6C5ogLbsxEqbPYBmQQAZBO9nKJF14yWGkzBK5ErOEAfPiQwicjAhlg0RDDk2KjAwGSJITgUkACsiJThRAFceZjh+bCVVdn4Y-gAPdkRhcxiARySsDFJdI0EARnZyyurBOJcYdk9vX1d3bp8-AKDCTm4wPiENKxtorLVprRlaw2M4i01rWTsHdpBnToHetxgeBAA3NAQeNgAZBBJkAHMO9jPzvpOjv2u2MCwVDJ0v8GGQZFg-lh8mB2NI5GALlgXG40GhgMAAMRYfhyKhoHiiUwAXyJKLQ+DApwuaDk6TMbBk-G4cAAtE8MMkZMikKjURSqZdafx6YRGcy0GKcCyeFhmPwknB6PsybzyZT3jS6UQGUypTR+GckC9lTzeRTzZSqAAWTXC7Wi3WshFgCjc1XutUwfj4-hgfgssCiJ5PChsZRwdLhJEgRgsNgY9EAfWuJJc6IASuIVAIVFgSZ1+H0+fQS-z2Nai2qLZ13pWPeiMQhmGhROCkAB1ZAEgDu8QoRrAeOcaH0qdNHv5GqFIpAMg57MoRDdHrN6up0-ts-n2DMLOEGQl28Xe4yLKISTkckXDA5odFR7M+4wDBI5AhhG710HkDRwFbWA7LtRF7QR+yeQd2E-JAeyINAACo0HqfR9DQEkAFI02AABZX0qEEDkkmggAKf9AOg4C+wA8CqEgoDe3gxDkIASlQok0M1UQiCwHg0E7cjexrC4DinLUGQfIgTwwQ8gx3CSn2lJkniqF8yDvEBPx4b90SQ-QWVIviYNAqiIKgmCGJ09DXlrQSPnRdgmzHFc0Bsut3QFK4bkIJMU1JGMNx1ZkWXDSMuJpUQI1kLiOgVZwG30uiiHzRBYuAUzgJ8zpkrs+L+MSolOhiskXLJOzsVxRzyVNGBhCSUJRB5eqgsQOQUDYbAr0RFxcUUrA0DSgT1FqwMkD6Q4vEGZwQAAGmIKAYzQCg-AJUw0FwNAAG1gBVNBkx4H9CAAJgOq19AOrAAA4dBZc65HqK6rR0YQADYWX4A7zoAVhZA65HOrAAE4dHqLAAHZ+GEc7CCm7bM1UHMsH2kAABVKGsLMoe2nKYJ-dbtopVK6OuRH6gOnQrUIIlofHXkCf4onyRAUmrQ+imqfrfr6cID6Pqep7We2gBdNneX6iI0BZ01KeAXbEaOk6zsu67bvux6Xrez7vt+gHmdBjAwHJ6aYazeHEZRqQszQA6MeprGKJxvGwFpntOZAZmdCtkBKe21EnfSvaGaO+p6gpwXhdRUWf0hyXvbQAWAG43DcRa0BUUh0xxBFzl6tbuG7NB0-hREiK200cB-AByDF7keI1y+F-5AWBBG0ErhugV9LA67JHhfX4SBgGWxLhfq-vtvarBER-ZhCML+qiKYkuPXOA9B9WmkqB6ogAEkkGUewjXnhPqdRZhRAwIiECuHlB4XmPUWUJAiHCrBQKDIjy+Wq4xbr-FCSIdaEACyYkfCkHpBwPEEDIJI1B36Dx-oPABQCj4elJNTVBqJUFEmAW4aeu8ET1XXpvHee9njzzRNtTgNBsAp1IIQo0lA0CyHBBkMk2AwBJAwDyTa20ZYMznCyb6x1ToXSujdO6LIHrPVeu9L6P0-qA2BmDCG1tVSw2zPwXMptUYclUCo3kttez22pvjDm-tCAkzJvzY+aJTGyzJizT2odtoR3FmSKWvD7wCLlsIxWYiVZSPVrIrW-0dZKMhobamaiTYMzNmjVQHsw4tjbAZO2G0Ha+w0ojN2HsvbWIyS7QOwdPaJJ9rYgOB0SZWPZoTMxjMKk6Cqe6fJtTA4G1yaqIWziEqRzcTHeObgiTTRAHIOaQyqBQFABgOa9QDCeyJEAA)

My version is not behaving exactly as yours, but I think that's normal since we are pushing different documents (`_id`'s differ). 

As a CouchDB user, I prefer using objects and manipulating the properties, then call `this.update('myobj')`. This will provide `magic=true` look and feel, plus it will be more declarative.

**Comment by wgrhstf** [comment] 2018-10-03 08:02
That's an interesting approach as well. The real script is in fact a CouchDB/PouchDB thing where updates are based on [this](https://pouchdb.com/2015/02/28/efficiently-managing-ui-state-in-pouchdb.html) idea by Nolan Lawson. The different `_id` values where just due to a lack of coffee and the setup is quite different from the real application as I could not use a couple of things in Playground.  I'll see if I am able to fiddle your approach in my original application...

**Comment by dagnelies** [comment] 2018-10-03 08:14
By the way, using `set()` to update the data is recommended. From my understanding, `update()` is more of a hack when something is out-of-sync because of external influence. You can also close the issue if you think your issue is "solved".

**Closed as completed** 2018-10-03 08:24 UTC
Labels: inquiry/question

**Comment by ceremcem** [comment] 2018-10-03 19:14
@dagnelies  
> By the way, using set() to update the data is recommended

It may not be the case: https://gitter.im/ractivejs/ractive?at=5b1e650b144c8c6fea893e4c
