### ISSUE TITLE
Elements in `if` and `else` blocks visible at the same time

### ISSUE THREAD

**Issue by MartinKolarik** [ractivejs/ractive#2027] opened 2015-07-04 11:27 UTC
See [this demo](http://jsfiddle.net/gc230cj9/) and click the button twice. Text nodes are removed immediately, but it seems that elements are waiting for the transition (which really has nothing to do with the if/else block) to complete.

**Comment by YRathod** [comment] 2015-07-22 21:25
Not able to reproduce with test html page but able to reproduce on jsFiddle only.

**Comment by evs-chris** [comment] 2016-04-27 06:01
Fixed in edge 😃

**Closed by evs-chris** 2016-04-27 06:01 UTC
Labels: bug, transitions
