### ISSUE TITLE
Decorators Teardown Called Before Event Handler

### ISSUE THREAD

**Issue by acl12345** [ractivejs/ractive#3050] opened 2017-08-08 22:37 UTC
## Description:
Decorators that add click event listeners to elements that also remove themselves from the DOM `on-click` in a Ractive component will call the decorator `teardown` (which removes the event listener). This only occurs on the first click on the element, and, thereafter, the click event handler will properly be called before teardown.

This behavior is not observed when the decorator is used in a new Ractive instance, only in Ractive components.

## Versions affected: 
Was able to reproduce in 1.0.0 build 49 (which I believe is the latest edge build), and likely earlier versions are affected.

## Platforms affected:
Happens in Chrome, Firefox, and Safari.

## Reproduction:
https://jsbin.com/dikadep/edit?html,js,output

The following conditions are needed to reproduce:
* Decorator that adds event listener to node, while teardown removes event listener.
* Decorator applied to an element that removes itself from DOM in a Ractive component.

In above JSBin, the buttons add 'A' or 'B' into a list in the click event handler and swaps to the other letter in the DOM. The above section is the decorator with a Ractive instance and the below section with a Ractive component. The expected output when clicking the buttons is "A,B,A,B,..." but the Ractive component side skips the first 'A'. This is because the decorator handler's `teardown` function is called first. If you look at the console, you can see that the teardown function is called when you first click the button.

**Comment by evs-chris** [comment] 2017-08-09 06:06
This was caused by event directives not being subscribed as a deferred task because of a derp with an arg to `forEach`. This should now be fixed in edge and will be pulled down to 0.9.4 when it's cut. Thanks for the report!

**Closed as completed** 2017-08-09 06:05 UTC
Labels: bug/major
