### ISSUE TITLE
0.8 - array observe changed behavior

### ISSUE THREAD

**Issue by kouts** [ractivejs/ractive#2594] opened 2016-06-23 16:51 UTC
Check this fiddle http://jsfiddle.net/65k2w8a4/7/
I'm using the toastr jquery plugin to display some messages.
On 0.73 and up until v0.8.0-edge-ed9564e3f95e9befe619b92ed35e3a46375164f7 the array
gets observed once.
This is now changed on edge.

You can switch between edge and 0.73 on jsfiddle.net to see the difference.

**Comment by evs-chris** [comment] 2016-06-23 17:06
I think that was actually a bug in 0.7.3. When you set the array at the end of the observer, it is firing again because its observed value changed. In 0.7.3 that got lost because observers were already running and the runloop ignored any non-view changes.

In this case, I think locking for the empty set or ignoring empty values would be a reasonable approach. I think the observer should always fire, though, even if it caused itself to do so. Anyone else?

**Comment by martypdx** [comment] 2016-06-23 18:40
@evs-chris would an individual observer allow re-entrant calls? I think the original intent was to prevent infinite loops, so dev would just need to be aware.

**Comment by kouts** [comment] 2016-06-23 19:51
At first it seemed like a bug to me too, I didn't knew it was intentional.

**Comment by evs-chris** [comment] 2016-06-23 20:17
I changed it while handling one of the 'observers are broken' issues because someone _was_ expecting it to fire and it wasn't. I don't recall seeing anything specifying that observers couldn't be re-entrant, but I don't see any reason we couldn't add a lock on the observer to keep it from firing itself _directly_. IIRC the issue that allowed observers to be triggered more than once was happening after the observer round completed and a fragment caused a new keypath to grow.

So I propose we add an option to `observe`, `reentrant: false`, and a locking mechanism on the observer to keep it from firing itself if it's not reentrant. Does that sound reasonable?

**Comment by kouts** [comment] 2016-06-23 20:24
That sounds fine! But what would be the default?

**Comment by evs-chris** [comment] 2016-06-23 20:34
`false` so it wouldn't be (or would be less?) breaking :smile:

To get reentrant behavior, you would have to `r.observe('some.key', () => {}, { reentrant: true })`

**Comment by kouts** [comment] 2016-06-24 05:56
Ok so one more option for observers then!

**Comment by evs-chris** [comment] 2016-06-27 03:31
When I went to create a failing test for this, I discovered that it was actually just a regression that appeared during the observer bugfixing. The bug is now fixed in edge, so I'll punt on the re-entrant thing until it comes up again :smile:.

**Closed by evs-chris** 2016-06-27 03:31 UTC
Labels: pending-clarification

**Comment by kouts** [comment] 2016-06-27 06:22
Ok so this was a bug after all :smile:
