### ISSUE TITLE
Typings  on later versions

### ISSUE THREAD

**Issue by enneid** [ractivejs/ractive#2973] opened 2017-05-25 11:41 UTC
Now there are only ts declarations for 0.7 version. It will be nice if it appears for  0.8, 0.9 or edge

**Comment by ghost** [comment] 2017-05-25 12:07
Looks like a duplicate of https://github.com/ractivejs/ractive/issues/2969

Yep, we're trying to update it. 😄

**Closed as completed** 2017-05-25 12:07 UTC
Labels: no action/duplicate
