### ISSUE TITLE
Feature request: short expressions

### ISSUE THREAD

**Issue by matthew-dean** [ractivejs/ractive#2149] opened 2015-09-17 17:28 UTC
I find myself writing this **a lot**.
```
<div class="{{ .some_property ? 'active' : '' }}">
```
I find having to write ```:''``` a dozen times wasteful. Twig offers a convenience syntax for this. You can write the equivalent expression as:
```
<div class="{{ .some_property ? 'active' }}">
```
You can also write an expression for the common ```foo ? foo : 'no'``` pattern as:
```
<div class="{{ foo ?: 'no' }}">
```
Would it be possible to get these added to Ractive expressions? At the least, the first one?

**Comment by MartinKolarik** [comment] 2015-09-17 17:57
`foo ?: 'no'` can be written as `foo || 'no'` in JS, but I think that `.some_property ? 'active'` would be useful and probably very easy to implement.

**Comment by JonDum** [comment] 2015-09-17 20:01
@MartinKolarik I don't think you can do that in an expression though, it's going to output `"true"` as a string when `foo` is `true`. And vice versa for `foo && 'yes'`. http://jsfiddle.net/jondum/2f0064ev/

A possible easy solution would be to not cast booleans to strings, then you could do both of those without outputting "true" and "false" to the DOM.

**Comment by martypdx** [comment] 2015-09-17 20:22
> @MartinKolarik I don't think you can do that in an expression though, it's going to output "true" as a string when foo is true. And vice versa for foo && 'yes'. http://jsfiddle.net/jondum/2f0064ev/

I think the original ternary was `foo ? foo : 'no'` which would also output `true`, so I think `foo || 'no'` is correct

**Comment by evs-chris** [comment] 2015-09-17 20:51
The second, while redundant, is ok, but I personally don't like that the first looks like an incomplete ternary. Perhaps `.some_property ?? 'active'`?

**Comment by matthew-dean** [comment] 2015-09-17 21:07
@evs-chris I've seen ```.some_property ?? 'active'``` in another templating library but couldn't remember where so I didn't mention it. That form would work too I think.

**Comment by heavyk** [comment] 2015-09-17 21:28
I often times use the syntax, `something && 'is true' || null`
the same can be done with ternary, `something ? 'is true' : null`

(dunno why but my eyes don't ever really "see" the ternary expression)

http://jsfiddle.net/5cwnthrx/

**Comment by thomsbg** [comment] 2015-09-17 21:36
How about simple inline conditionals instead? `{{if (prop) 'active'`.

Of course, include `unless` and perhaps the suffix variant: `{{'active'
unless disabled}}`

**Comment by heavyk** [comment] 2015-09-17 21:45
mmm, well personally, I like the idea of saying `something && 'is true'` or `something || 'is false'` and having ractive add on to the end of the expression "|| null", to not have it output the `true` or `false` value.

hmmm, that could be really easy to implement...

**Comment by matthew-dean** [comment] 2015-09-17 23:04
> mmm, well personally, I like the idea of saying something && 'is true' or something || 'is false' and having ractive add on to the end of the expression "|| null", to not have it output the true or false value.

That seems reasonable and straightforward, too. I don't think outputting "false" or "true" as a string value makes much sense IMO.

**Comment by fskreuz** [comment] 2015-09-18 20:00
Throwing in my 2c, I think Ractive should stick to plain JS expressions as much as possible. Ternary ain't that bad. It's readability, familiarity and future-developer friendliness in the expense of a few keystrokes.

Saying this in comparison with Angular, which uses a lot of special expressions in directives that you can't wrap you head around what really runs between those quotes. Worse, directive authors variably use `&`, `@` and `=` - luckily we don't have to deal with this in Ractive.

Speaking of Angular, this scenario is solved with `ng-class`. One could just create a decorator that acts like `ng-class`.

**Comment by JonDum** [comment] 2015-09-18 20:43
Yea ng-class is nice. But in ractive creating a similar sugar has its own
set of problems.

For example, I sometimes use something like:

```
<div class='{{classes}}'>
```

```
        classes: function() {

            var c = {
                type: this.get('type'),
                selected: this.get('selected'),
                dragging: this.get('dragging'),
                ... other stuff
            };

            return reduce(c, function(a, b, p) {
                if(isString(b) && b.length > 0)
                    return a + b + ' ';
                else if(b)
                    return a + p + ' ';
                else
                    return a;
            }, '');

        },

```

But you have to be super careful with your dependancies. If you have many
other computed properties that are calculation heavy, and you have 100
things on the screen, well it's actually some noticeable lag when ractive
goes through recalculating *all the other dependencies* because a single
dep changed. So this isn't a great solution in a lot of cases.

**Comment by martypdx** [comment] 2015-09-18 21:49
I don't see a lot of value using string building via javascript expressions and prefer to stick to straight mustache interpolation for classes. Most elements worth denoting with a conditional class typically have at least one static class as well, so it reads much better IMO to use declarative blocks:

```handlebars
<div class='myClass {{#if someProprety}} active {{/if}}'>...</div>
<div class='otherClass {{#unless foo}} no {{/unless}}'>...</div>
```

(If you're into minimalism you can always change delimiters and use the straight mustache syntax :)

```html
<div class='myClass {#someProprety}active{/}'>...</div>
<div class='otherClass {^foo}no{/}'>...</div>
```

I've found using whitespace via indented blocks is really helpful for more complex logic:

```handlebars
<li class='layout-item
		   {{#if i >= start && i <= end }}
		       sliding
		   {{/if}}
		   {{#if cardstyle.inverse }}
		       inverse
		   {{/if}}'
	style='{{#if isTile }}
			   width: {{ cardview.width }}px;
	 		   height: {{ cardview.height }}px;
	 	   {{/if}}}'>
```

I did I asked around the interwebs to see what could be brewing for future ES, but beyond existential operator (`foo?.bar`, which isn't necessary in Ractive templates) there wasn't much consensus for this case. 

You could certainly make an argument that ternary expressions are simply "omitable" (including the trailing `:`) in templates and thereby convince ourselves it's still normal javascript :). But given I use what I outlined above, I don't have a strong opinion, though I tend to share @fskreuz's preference for sticking with vanillaJS.

**Comment by evs-chris** [comment] 2015-09-18 22:31
FWIW, I think the existential operator would be pretty handy for expressions. It would keep things from throwing if you don't account for undefined in your path that has an `||` trailing it.

**Comment by martypdx** [comment] 2015-09-18 22:55
@evs-chris agree in expressions esnext syntax is nice.  I was referring to template references.

**Comment by Rich-Harris** [comment] 2015-09-22 20:28
I do find the `:''` bit annoying as well, but despite that my preference is also to stick with vanilla JS. For me the crucial consideration is this: if I were learning a new library and discovered that it had this shortcut syntax I hadn't seen anywhere else, I'd immediately start wondering what other non-standard things it had. And then I'd become anxious, because in order to use the library as intended by its creators, I'd presumably have to go and learn (and remember!) all those little quirks, and I'd have to remember that I *couldn't* use those tricks outside of the Ractive template environment (or worse, if I was learning JavaScript, I might assume it was legit code and start using it elsewhere, struggling to understand the errors I was generating).

@fskreuz makes a good point about future-friendliness as well – `foo ? bar : ''` will *always* mean the same thing to all JavaScript developers.

Here's a possible alternative: http://jsfiddle.net/p3vxpz4n/ – similar to computed properties but more generic, and you can see them in the template. At least in this example, clicking the checkboxes in the first row wouldn't cause the second and third ones to re-evaluate. (Would be nicer if we supported ES6 shorthand properties in expressions...)

**Comment by kouts** [comment] 2015-09-23 07:34
+1 for vanilla JS, for the exact same reasons, @Rich-Harris stated.

**Comment by matthew-dean** [comment] 2015-09-23 14:52
@Rich-Harris @kouts Note that some of the suggestions here were also plain vanilla JS. e.g. the ```foo && 'bar'``` & ```foo || 'bar'```. The only problem with those is that Ractive is outputting "true" and "false" as string values as a result of either expression, which seems rarely valuable. I could see it outputting "truthy" values, but maybe a compromise would be to not output booleans as strings, as suggested?

**Comment by Rich-Harris** [comment] 2015-09-23 15:10
@matthew-dean I wondered about that, but that too would be confusing. Consider a situation like this:

```html
<div class='progress-outer'>
  <div class='progress-inner' style='width: {{progress * 100}}%;'></div>
</div>
```

Should `{{progress * 100}}` be rewritten as `{{'' + (progress * 100)}}` so that it's a string and not a number? What about an object that has a useful `toString()` method, such as a `Date` object – should *that* be ignored because it's not a string? There are *lots* of times when coercion is useful.

We could make an exception for booleans, because they're *less likely* to be useful. But that'd be really surprising if you were, say, doing some debugging (I often rely on booleans in this context). It would be another thing to have to learn, and another source of frustration if you forgot.

Ultimately, my guide in these matters is the behaviour of mustache.js, since Ractive's templating language aims to be backwards-compatible with Mustache. And there, the only values that aren't coerced are `null` and `undefined`:

```js
Mustache.render( '{{foo}}', { foo: 'hello' }); // 'hello'
Mustache.render( '{{foo}}', { foo: 1 }); // '1'
Mustache.render( '{{foo}}', { foo: new Date() }); // 'Wed Sep 23 2015 11:08...'
Mustache.render( '{{foo}}', { foo: NaN }); // 'NaN'
Mustache.render( '{{foo}}', { foo: null }); // ''
Mustache.render( '{{foo}}', { foo: undefined }); // ''
Mustache.render( '{{foo}}', { foo: true }); // 'true'
Mustache.render( '{{foo}}', { foo: false }); // 'false'
```

**Comment by heavyk** [comment] 2015-09-23 16:36
I would like to add, that as a noob, the first thing I tried in most cases was `foo && 'foo is truthy'`. I use that often in string concatenation.. I also use `foo || 'foo is not truthy'` and that works as expected, assuming foo is what I want to print. often times I use it like this

```html
<div style="height: {{height || 10}}px">...</div>
```

right now I usually use the && like this:
```html
<div class="{{active && 'activated' || null}}">...</div>
```

if I could get rid of the `|| null` bit, that'd be nice. so, I propose two ideas:

1. only in the situation where the final expression in the chain is `... && blah`, then the expression would be appended with `|| null`. (becoming `... && blah || null`). (see http://jsfiddle.net/ttpdg3dL/)

 - the reason why I don't believe this is a problem for beginners is because I can't think of a situation (debugging or otherwise) where I would want to see 'false' printed out instead of an empty string. it seems more natural to see a 'true' printed than to see a 'false' printed.

2.  perhaps as an option, just as mustache symbols can be changed, there could be an option coerce all non-numeric falsey values to empty string.

both of these would solve a minor inconvenience of a new characters' savings. and, after thinking it over, I like the second option much more than the first. I believe it wouldn't be too difficult to implement either (though I have not looked).

**Comment by martypdx** [comment] 2015-09-23 17:17
A few observations:

1. More ES6 in expressions FTW
2. Ractive's extensibility is awesome and you can tailor the API on your own (
see http://jsfiddle.net/uv3d8hbz/3/):

```js
suppressBool = {
  filter: function ( object, keypath, ractive ) {
    return typeof object === 'boolean';
  },
  wrap: function ( ractive, object, keypath, prefixer ) {
    return {
      teardown: function () {},
      get: function () { return object ? ' ' : ''; },
      set: function ( property, value ) {},
      reset: function ( data ) {
        if ( typeof data !== 'boolean' || data !== object) {
          return false;
        }
      }
    };
  }
};
```
(there's a bit of a hack using ' ' for true as expressions currently consume _adapted_ values, which probably shouldn't be the case. But for things like classes and other areas where extra whitespace isn't relevant, it shouldn't be an issue)

**Comment by heavyk** [comment] 2015-09-23 17:29
@martypdx holy shit that's awesome :)

**Comment by Rich-Harris** [comment] 2015-12-05 23:27
Will close this as consensus appears to favour vanilla JS

**Closed by Rich-Harris** 2015-12-05 23:27 UTC
Labels: enhancement
