### ISSUE TITLE
Update "progress-bar" based on selected element

### ISSUE THREAD

**Issue by vnmshenoy** [ractivejs/ractive#2189] opened 2015-10-03 02:14 UTC
I am new to Ractive.js. What i am basically trying to achieve is that based on the id selection(from the combo box),update appropriate progress bar.

In below sample, there are two progress bars and 4 buttons(+25,+10,-25,-10).User can select any progressbar(say "first") and then press any buttons like +25 etc.When the user performs this action, appropriate progressbar should be updated(in this case "first" by say "25").

I have tried but am not sure how to select context based on progressbar selection.In my case,both progress bars get updated irrespective of what i have selected in select box. Please let me know how can i resolve this issue and also tell me if there is a way to clean the code(something like ng-repeat etc)

Please see the code  below
(http://jsfiddle.net/shenoyvnm/awh5v9p6/)

<!doctype html>
<html lang='en-GB'>
<head>
  <meta charset='utf-8'>
  <title>Ractive test</title>
</head>
<style>

.progress-bar {
  position: relative;
  width: 200px;
  height: 40px;
  border: 1px solid black;
}
    
.progress-bar-fill {
  height: inherit;
  background-color: orange;
}
    
.progress-bar-fill-red {
  height: inherit;
  background-color: red;
  
}
    
.progress-label {
  position: relative;
  top: 3px;
  left: 5px;
  color: #000;
}

input[type=range] {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  cursor: pointer;
  /* essentially making range slider invisible */
  opacity: 0;
}

</style>
<body>
  <h1>Ractive test</h1>

  
 <div id='container'></div>
 <script id="template" type='text/ractive'>  
  <h1>I am a progress fill.</h1>
  <p>Slide or click to adjust my progress.</p>
    {{#if progress<100}}     
          <div class="progress-bar-fill" style="width: {{progress/2}}%">
          <span class="progress-label">{{progress}}%</span>
    </div>
    {{/if}}
    
     {{#if progress>=100}}
     <div class="progress-bar-fill-red" style="width: 50%">
     <span class="progress-label">{{progress}}%</span>
     </div>
     {{/if}}
    <br> 
    
    <p>Slide or click to adjust my progress.</p>
    {{#if progress1<100}}
    
    <div class="progress-bar-fill" style="width: {{progress1/2}}%">
    <span class="progress-label">{{progress1}}%</span>
    </div>
    
    {{/if}}
    
    {{#if progress1>=100}}
    <div class="progress-bar-fill-red" style="width: 50%">
    <span class="progress-label">{{progress1}}%</span>
    </div>
    {{/if}}
     
    <select value='{{selectedProgress}}'>
      <option selected disabled>Select something</option>
    {{#progressbars}}
      <option value='{{id}}'>{{name}}</option>
    {{/progressbars}}
 </select>
   <button on-click='plusTwentyfive'>+25</button>
   <button on-click='plusTen'>+10</button>
   <button on-click='minusTen'>-10</button>
   <button on-click='minusTwentyFive'>-25</button>
</script>
   <script src='http://cdn.ractivejs.org/latest/ractive.min.js'></script>

  <script>
  var ractive = new Ractive({
  el: document.body,
  template: '#template',
  data: {
    readonly:	false,					
    progress: 	0,
    progress1: 	0,      
    progressbars: [
            { id: '0', name: 'first' },
            { id: '1', name: 'second' }
         
            // and so on...
    ]
  }
}); 
   ractive.on({
      plusTwentyfive: function () {
      var progress = ractive.get('progress');      
      progress=progress+25;
      ractive.set( 'progress', progress);
          
      var progress1 = ractive.get('progress1');      
      progress1=progress1+25;
      ractive.set( 'progress1', progress1);
  
  },
      plusTen: function () {
      var progress = ractive.get('progress');
      progress=progress+10;
      ractive.set( 'progress', progress);
          
      var progress1 = ractive.get('progress1');
      progress1=progress1+10;
      ractive.set( 'progress1', progress1);  
  },
       
      minusTen: function () {
      var progress = ractive.get('progress');
      progress=progress-10;
      if(progress<0)
      {
        progress=0;
      }
      ractive.set( 'progress', progress);    
      
      var progress1 = ractive.get('progress1');
      progress1=progress1-10;
      if(progress1<0)
      {
        progress1=0;
      }
      ractive.set( 'progress1', progress1);  
  },
          
    minusTwentyFive: function () {
          var progress1 = ractive.get('progress1');       
          progress1=progress1-25;
         if(progress1<0)
          {
              progress1=0;
          }

          ractive.set( 'progress1', progress1);

      }
});
</script>
</body>
</html>

**Comment by evs-chris** [comment] 2015-10-03 02:17
I don't think your example made it. Can you put up one up on jsfiddle.net to make it a little easier to see what you're looking for?

**Comment by vnmshenoy** [comment] 2015-10-03 02:18
Thanks,yeah i have added the jsfiddle link (http://jsfiddle.net/shenoyvnm/awh5v9p6/)

**Comment by heavyk** [comment] 2015-10-03 03:23
you have some work to do. you need to make `progress` an object for the progress values (the ids should correspond to the object keys and remember to initialize them to 0). then, you should add or subtract from values in the object based on the ids in your functions.

I'd also print out the bars in an each loop too

```html
{{#each progress:id}}
progress bar {{id}}: {{progress[id]}}
{{/each}}
```

**Comment by evs-chris** [comment] 2015-10-03 03:26
That's a pretty complex example. I reduced functionality a bit (no bounds checking) to simplify the code some: http://jsfiddle.net/awh5v9p6/1/. I added the progress tracking into the data, but if you want to avoid that, you can use a reference expression as described by @heavyk.

**Comment by heavyk** [comment] 2015-10-03 03:56
your way is cleaner. I suggested to use the id as a key, that way bounds checking can be done in a custom add/subtract function. you will notice that you can easily get negative values (which also can be solved by if-statements in the template, if you desire :D lol)

**Comment by vnmshenoy** [comment] 2015-10-03 03:59
Thanks @heavyk and @evs-chris 

@evs-chris - Could you please help me understand why {{which}} is used in your egample. I mean the select part. I have gone through the site documentation but didn't find it that helpful.

@heavk- Thanks for your answer too.

**Comment by heavyk** [comment] 2015-10-03 04:01
which is the name of the variable. it references the progressbar selected

**Comment by heavyk** [comment] 2015-10-03 04:07
more specifically (keep forgetting your new) - if you look at the options see that their values are: `value="progressbars.{{@index}}.progress"` -- what that means is the `which` variable is set to a keypath...

when you select the first one, which will equal `progressbars.0.progress` so then when the add or subtract function is called from the button, it will add or subtract from that keypath. you can see that inside of the data, there is an array of `progressbar` and inside of each one, one of the values is `progress` ... that's what's being changed.

try modifying its value to something other than 0.

**Comment by vnmshenoy** [comment] 2015-10-03 04:49
Thanks for explanation.And i got it to some extent. And one more thing, when you say keypath,is it like setting the context for the selected id?

**Comment by heavyk** [comment] 2015-10-03 04:51
yeah, it'd be just the same as writing `this.add('progressbars.0.progress', 25)` -- try it :)

**Comment by heavyk** [comment] 2015-10-03 04:52
sorry, in the fiddle write `ractive.add('progressbars.0.progress', 25)` to try it

**Comment by vnmshenoy** [comment] 2015-10-03 06:30
got it thanks +1

**Comment by vnmshenoy** [comment] 2015-10-03 06:31
btw is there any good documentation for this

**Comment by heavyk** [comment] 2015-10-03 10:48
not really at the moment, but as I've been tracking the ractive project, I think I may want to begin fitting myself more into the documentation aspect of the project. I see that (for me) it's the most rewarding, and also the most needed.

so, it is my goal to eventually improve that aspect soon. unfortunately, you don't really get a sense of how to use ractive until you've seen a million fiddles and played around with it a lot on your own.

for now..keep trying things and keep asking questions. get involved a bit too if you want. it's the fastest way to learn

**Comment by Rich-Harris** [comment] 2015-10-03 17:54
This is a dupe of [this StackOverflow question](http://stackoverflow.com/questions/32917418/update-progress-bar-based-on-selection-in-ractive). @vnmshenoy please don't post questions to more than one venue, as you'll waste the time of people trying to help you. At the very least, indicate that the two questions are linked.

For reference, here's the solution I posted: http://jsfiddle.net/rich_harris/k8vpcv27/

**Closed by Rich-Harris** 2015-10-03 17:54 UTC
Labels: question

**Comment by vnmshenoy** [comment] 2015-10-04 02:05
Thanks
