### ISSUE TITLE
keypaths breaking on unshift in edge

### ISSUE THREAD

**Issue by aphitiel** [ractivejs/ractive#1737] opened 2015-02-19 16:29 UTC
See http://jsfiddle.net/4ukh3aqu/

After clicking `add1` the results of `{{@keypath}}` break for items existing before the unshift. Clicking `log` shows that event.keypath is still ok, except for that "special" case.

Push works as expected, as does latest.

**Comment by aphitiel** [comment] 2015-02-19 19:57
Issue starts with commit 7bf0d176394bf8a1aa1aeab35177ada4f03bad39 on branch edge, which seems to be based on 5ca8675c.

Sadly, I can't get that to build: `gobble: 02-esperanto transformation failed`
`EEXIST, file already exists '/home/aphitiel/git/ractive/.gobble/02-esperanto/.cache/Ractive.js.map'`
Any quick ideas?

**Comment by Madgvox** [comment] 2015-02-19 20:54
This looks like it might be the same issue as https://github.com/ractivejs/ractive/issues/1729.

**Comment by evs-chris** [comment] 2015-02-20 14:50
It looks like this is partially caused by `@keypath` finding an expression context from the `#if` just above it. Should https://github.com/ractivejs/ractive/blob/dev/src/virtualdom/items/shared/Resolvers/SpecialResolver.js#L64 also check that the context doesn't start with `'${'`?

**Comment by martypdx** [comment] 2015-02-20 15:41
> finding an expression context from the #if just above it.

I didn't think that `#if` blocks created context. Do they?

> check that the context doesn't start with '${'

But wouldn't it be valid to do: `{{#each getArray(foo)}}{{@keypath}}{{/each}}`?

Also, for reference, we have similar logic in [`Binding`](https://github.com/ractivejs/ractive/blob/dev/src/virtualdom/items/Element/Binding/Binding.js#L17-L20) that checks the end of the keypath for `}` because it's perfectly valid to bind to a property of the result of an expression. So, you could have `{{#with condition ? obj1 : obj2 }}{{#each .property}}{{@keypath}}{{/each}}`

**Comment by evs-chris** [comment] 2015-02-20 15:46
I didn't think they did, but stepping through, it looks like that's the issue.

I don't think you can really do anything with an expression context, like `set` with it, so is it useful as a ref beyond just displaying it?

**Comment by martypdx** [comment] 2015-02-20 16:03
In my mind, it's not whether or not they're expressions, it's that conditional blocks don't change or create context they just control inclusion/exclusion of template content. Take it out and see what breaks :)

**Comment by aphitiel** [comment] 2015-03-02 22:00
Some observations:
* There might be 2 different problems in http://jsfiddle.net/4ukh3aqu/:
 1. @keypath ```items.1.tags.0``` becomes ```items.1``` after unshift. This does not affect ```event.keypath```, and may be related to SpecialResolvers, though I haven't looked yet.
 2. keypath ```items.1.tags.0``` becomes ```${items-2-tags-0-title==="twoOne"&&poipoi-items-2-tags-0-title-}``` for fragments(?) inside the conditional. This does affect ```event.keypath```
   * Does not happen when using only restricted references (changing ```{{#if .title === 'twoOne' && poipoi[title]}}``` to ```{{#if .title === 'twoOne' && poipoi[.title]}}```)
    * When it happens, ```resolveAndRebindChildren``` calls ```f.rebind```, which calls ```assignNewKeypath(this, "context"``` with keypaths like ```${items-2-title==="two"&&poipoi-items-2-title-}```, which might be problematic.
     * Changing ```f.rebind(oldKeypath, newKeypath);``` to ```if (mustache.subtype !== 50) { f.rebind(oldKeypath, newKeypath); }``` /seems/ to fix the problem without breaking tests. But sadly I have no idea what I'm doing.

Does that make any sense to anyone?

**Comment by evs-chris** [comment] 2015-03-11 20:59
Fixed in #1795

**Closed by evs-chris** 2015-03-11 20:59 UTC
