### ISSUE TITLE
Binding a linked property to a component result in unexpected behavior

### ISSUE THREAD

**Issue by pietervisser** [ractivejs/ractive#2924] opened 2017-04-05 14:01 UTC
## Description:
When binding a linked property to a component, evaluation of nested properties does not work inside that component

## Versions affected:
0.8.12

## Platforms affected:
Chrome, Safari, Firefox

## Reproduction:
 http://codepen.io/depietervisser/pen/PpgREr

**Comment by ghost** [comment] 2017-04-05 14:25
Not sure how the internal mechanisms work for `ractive.link`, but it appears that linking during `oninit` makes it "too late" to link. [Moving the linking to `onconfig`](https://codepen.io/anon/pen/zZXLZz?editors=0010) appears to work. Further debugging shows that [inputs appear to get the correct value as well as sync](https://codepen.io/anon/pen/peBZrb?editors=0010). It might be an issue with the sections.

If a workaround is ok, you can take the `onconfig` route until this is resolved. 😄

**Comment by evs-chris** [comment] 2017-04-05 15:38
It looks like there is a bug with relinking in 0.8 that doesn't exist in edge. When the components are created, their mappings set up appropriate links, including to the empty `linked_item` model. Then when `init` fires and `linked_item` is linked to `company`, the deps on the empty model aren't completely transferred to the new target.

**Comment by evs-chris** [comment] 2017-04-05 17:41
Well, I was close. The deps are transferred, it was just missing a full invalidation cycle. The fix is now available in 0.8-dev and will go out with 0.8.13 when it is cut. I've also added the regression test to edge. Thanks for the report!

**Closed as completed** 2017-04-05 17:41 UTC
Labels: bug/major

**Comment by pietervisser** [comment] 2017-04-05 17:52
Thanks!
