### ISSUE TITLE
Dynamic Components

### ISSUE THREAD

**Issue by lucasmotta** [ractivejs/ractive#1743] opened 2015-02-20 15:19 UTC
Is it possible to use something similar as the Vue.js dynamic components?
http://vuejs.org/guide/components.html#Dynamic_Components

The example on the Vue.js website is pretty explanatory.

It's much better to write this:
```html
<div component="{{componentName}} />
```

then:
```html
{{#if componentName == 'home'}}
<home />
{{/}}
{{#if componentName == 'about'}}
<about />
{{/if}}
{{#if componentName == 'contact'}}
<contact />
{{/if}}
 

Or is there a similar alternative for this?

**Comment by martypdx** [comment] 2015-02-20 16:01
Not currently _in the template on the component tag_ directly. You can do it in the options if it is only going to be selected on initial render:

```js
// assuming home, about, and contact are registered components
components: {
    dynamic: function(){
        return this.get('componentName');
    }
}
```
```html
<dynamic/>
```

If you need true dynamism, you can do a pretty good job with dynamic partials (see http://jsfiddle.net/rm95Lj48/):

```js
Ractive.prototype.data = {
    getComponent: function(name){
        if (!!this.partials[name]) return name;
        this.partials[name] = '<' + name + '/>';
        return name;
    }
}
```

```html
{{>getComponent(componentName)}}
```
I'm hoping we can eventually have that same awesome dynamism @evs-chris put into partials, for the component tags, then you could just do:

```html
<componentName/>
```

**Comment by Rich-Harris** [comment] 2015-02-20 16:07
Something like this could have been pretty useful on my last project... I'm conflicted about what exactly it should look like, on the grounds that you should ideally be able to look at a piece of template and feel confident about what it's going to do. But the general idea of dynamic components is one I think we should pursue.

I'm going to close this issue though, as it's effectively a duplicate of #1678

**Closed by Rich-Harris** 2015-02-20 16:07 UTC

**Comment by ChadKeating** [comment] 2016-08-10 14:57
`components: {
    dynamic: function(){
        return this.get('componentName');
    }
}`

Sorry for the necro but it doesn't look like this method works with Ractive.js v0.8.0-edge
Is this this intended or a bug?
@evs-chris

**Comment by evs-chris** [comment] 2016-08-10 20:54
I'm pretty sure this is a bug. It looks like we're updating the registry with the result of the call when we shouldn't be. I'll put together a test and see what shakes out.

**Comment by evs-chris** [comment] 2016-08-10 21:04
Well, according to the test suite, components chosen by function like this are meant to remain pinned until the instance is reset. At that point, it will re-evaluate and get new values. I'm not sure exactly why it was done that way, but it seems to be on  purpose.

**Comment by kouts** [comment] 2016-08-18 06:55
Yes it only works with reset() right now, @evs-chris do you think dynamic components would be something worth implementing in 0.8?

**Comment by evs-chris** [comment] 2016-08-18 15:57
Adding dynamism to components in the same way as partials has some interesting extra considerations. The easiest way to add it would be to have a flag on the element that should be a component to tell the component to bind on that name as a variable. Then when the variable changes, the component would be torn down and recreated with the new name. It would be difficult to use components with private state in that scenario because of the tear down/construct cycle. I think a better way to handle that would be to use manually managed instances and anchors, but for widget-style components that just deal with provided data, it would be fine.

This would also be a little more rough on performance than partials, because every element has the potential to be a component. So you wouldn't want to bind _every_ element name to look for a change. Partials get away with it because there are relatively few partials in any given template. Instead, I'd say that throwing in a sigil on the name (`<$dynamic foo="{{bar}}">...</>`), or perhaps mustaches `<{{dynamic}} foo="{{bar}}">...</>` would be pretty much required. Then there's the question of what to do with the closing tag. I guess treating it like a generic section close would be easiest, where it can contain whatever you want it to from `</>` to `</$dynamic>` or `</{{dynamic}}>`.

I think new features should go in 0.9, even if 0.9 is pretty much ready to go as soon as 0.8 is out.
