### ISSUE TITLE
Ractive Edge computed/onchange/adaptor bug

### ISSUE THREAD

**Issue by Jeff17Robbins** [ractivejs/ractive#2717] opened 2016-10-26 00:51 UTC
## Description:

The 0.7.3 Ractive-Ractive adaptor relies on the Ractive `change` event and fully supports computeds.   Ractive Edge computeds still don't seem to fully work with this adaptor.
## Versions affected:

```
Ractive.js v0.8.1-build-5
Tue Oct 18 2016 15:28:26 GMT-0400 (EDT) - commit adbd4c06d169f8fcfbad1d5d7e42e3120f4e6934
```
## Platforms affected:

Windows 10 Chrome Version 54.0.2840.71 m
## Reproduction:

https://jsfiddle.net/5ws3mhwe/ 0.7.3 works

https://jsfiddle.net/0Lqw82x1/ 0.8 broken
## **Code:**

Two Ractive "store" instances:  `storeA` and `storeB`.  `storeA` has a simple data model with 'clock' in it.  a setInterval sets the value of 'clock' every second.

`storeB` has a computed named 'computedClock' dependent on `storeA`'s 'clock'.

Finally, a third Ractive instance, `view`, has as its template `{{StoreB.computedClock}}`.  

The three instances are wired together with a Ractive-Ractive adaptor that relies on the `change` event.

The 0.7.3 version has an updating milleseconds since 1970 on the screen, whereas the 0.8 version doesn't update past the initial value of 'clock', namely 0.

```
var storeA = new Ractive({
  modifyArrays: true,
  adapt: ['Ractive'],
  data: {
    clock: 0
  }
});
setInterval(function() {
  storeA.set('clock', new Date().getTime());
}, 1000);

var storeB = new Ractive({
  modifyArrays: true,
  adapt: ['Ractive'],
  onconfig: function() {
    this.set('StoreA', storeA);
  },
  computed: {
    computedClock: function() {
      return this.get('StoreA.clock');
    }
  }
});

var view = new Ractive({
  el: '#host',
  template: '{{StoreB.computedClock}}',
  modifyArrays: true,
  adapt: ['Ractive'],
  onconfig: function() {
    this.set('StoreB', storeB);
  },
});
```

**Comment by fskreuz** [comment] 2016-10-26 01:25
Doing a quick investigation, doing `this.get('computedClock')` from inside `storeB` (like in an `onchange`) gets the computed value right. But on `view` it gets `0`.

Furthermore, the `get` of the adapter only appears to be called once, most likely from `storeB` which might mean the adaptor is not working on `view`.

**Comment by evs-chris** [comment] 2016-10-26 02:30
This is caused by the updates to computations that make them fully lazy in 0.8. I'm about to move 0.8 into a maintenance branch and edge to 0.9, so there are two ways that I think we can address this:

1. I can add a flag to computations that makes them immediate (non-lazy), so you can specify that you _always_ want them to update whether they have deps or not.
2. You could switch to 0.9 edge, which at this point will basically be 0.8 without deprecated stuff and with a component API, support for more spreads, and more advanced yields. The build will be published to npm, so it won't change on you if you use the full version. I anticipate cutting 0.9.0 within 4 weeks if all goes well.

**Comment by Jeff17Robbins** [comment] 2016-10-31 01:12
We're definitely interested in the cross-instance `link(...)` capability of 0.9.  

In the meantime, I don't understand the dependency scheme well enough to know why my example doesn't work with lazy computations.  Is it the adaptor that messes things up?

**Comment by evs-chris** [comment] 2016-10-31 01:53
@Jeff17Robbins I don't know if this analogy helps any, but you could think of it kinda like a painting optimization. When the computation is invalidated (changes), if it's in the viewport that is being painted and isn't clipped (has dependents - things are registered to be updated when it changes - observers, mustaches, etc), it will be painted (re-computed).

The change event is entirely passive, so it can't trigger the recompute. The computation has to actually initiate a change event, and it will only do so if one of its dependents asks for the new value.

For my first suggestion, we could add a flag to compute so that it _always_ triggers a change event, even if it has no dependents:

``` js
new Ractive({
  ...
  computed: {
    foo: {
      get () { return this.get('some.value'); },
      eager: true
    }
  },
  ...
});
```

Currently what happens is `some.value` changes and invalidates `foo`, but there's nothing listening directly to `foo` changes (the change event doesn't count, cause it's passive) so no change event is fired. The `eager` flag would tell `foo` to go ahead and fire the `change` event when it's invalidated because it isn't lazy.

**Comment by Jeff17Robbins** [comment] 2016-11-04 16:59
re @evs-chris 's 2nd suggestion

`
You could switch to 0.9 edge, which at this point will basically be 0.8 without deprecated stuff and with a component API, support for more spreads, and more advanced yields. The build will be published to npm, so it won't change on you if you use the full version. I anticipate cutting 0.9.0 within 4 weeks if all goes well.
`

Here's the 0.9 version of an 'indirect' computed, working quite nicely with the new `.link(...)` ractive to ractive instance capability.  Nice!  Thank you @evs-chris !

https://jsfiddle.net/m1vsd02L/

**Comment by evs-chris** [comment] 2016-11-12 08:17
I'm going to close this for now. If the need arises, it will be pretty simple to add an `eager` flag for computations.

**Closed by evs-chris** 2016-11-12 08:17 UTC
Labels: adaptors, bug
