### ISSUE TITLE
Something very strange happened. Please file an issue at https://github.com/ractivejs/ractive/issues. Thanks!

### ISSUE THREAD

**Issue by paulocoghi** [ractivejs/ractive#1764] opened 2015-03-03 14:37 UTC
First, thanks for this incredible framework (I am planning a free course here in my city)!

The problem is the use of an `unless` with a data function. Here is my scenario:

```html
{{#each users:num}}

{{#if userRow(num) }}
<div class="row">
{{/if}}

	<div class="col-sm-5 {{ userClass(num) }} col-xs-12">
		<article class="profile-box">
			<span class="new-indicator">new</span>
			<section class="clearfix top">
				<figure class="image-box">
					<a href="/enterprise/profile/view/113659">{{#if avatar}}<img src="{{avatar}}">{{/if}}</a>
				</figure>
				<figure class="info">
					<h4><a href="/enterprise/profile/view/113659">{{name}} {{last_name}} , 30</a></h4>
					<h6>Just a description</h6>
					<span class="location"><figure class="icon pin svg" data-src="pin.svg"></figure>City of </span>
					<span class="match">85%</span>
				</figure>
			</section>
			<section class="bottom">
				<ul class="clearfix">
					<li class="addtofavorites"><a href="#"><figure class="icon star svg" data-src="star.svg"></figure>Add to favorites</a></li>
					<li class="message"><a href="#"><figure class="icon message svg" data-src="message.svg"></figure>Message</a></li>
					<li class="follow"><a href="#"><figure class="icon follow svg" data-src="follow.svg"></figure>Follow</a></li>
					<li class="share"><a href="#"><figure class="icon share svg" data-src="share.svg"></figure>Share</a></li>
				</ul>
			</section>
		</article>
	</div>

{{#unless userRow(num) }}
</div>
{{/unless}}

{{/each}}
```

And the Javascript:
```javascript
data: {
	users: [
		{ about: '', birth: '', name: 'Paulo', last_name: 'Coghi', avatar: 'images/people/profile02.jpg' },
		{ about: '', birth: '', name: 'Teste', last_name: 'Sobrenome', avatar: 'images/people/profile01.jpg' },
		{ about: '', birth: '', name: 'Teste 2', last_name: 'Sobrenome 2', avatar: 'images/people/profile03.jpg' },
		{ about: '', birth: '', name: 'Paulo', last_name: 'Coghi', avatar: 'images/people/profile06.jpg' },
		{ about: '', birth: '', name: 'Teste', last_name: 'Sobrenome', avatar: 'images/people/profile05.jpg' },
		{ about: '', birth: '', name: 'Teste 2', last_name: 'Sobrenome 2', avatar: 'images/people/profile04.jpg' },
	],


	userClass: function( num ) {
		return (num % 2 == 0) ? 'col-sm-offset-1' : '';
	},


	userRow: function( num ) {
		return (num % 2 == 0) ? true : false;
	},

},
```

**Comment by martypdx** [comment] 2015-03-03 15:30
You can't split tags like this with Ractive because it parses a DOM representation, not a string:

```html
{{#if userRow(num) }}
<div class="row">
{{/if}}

...

{{#unless userRow(num) }}
</div>
{{/unless}}
```

You can use a partial to achieve the same construct:

```html
{{#each users:num}}
    {{#unless (num % 2) }}
        <div class="row">{{>cellContents}}</div>
    {{else}}
        {{>cellContents}}
   {{/unless}}
{{/each}}

{{#partial cellContents}}
     <div class="col-sm-5 {{ userClass(num) }} col-xs-12">
     ...
     </div>
{{/partial}}

```

>  (I am planning a free course here in my city)!

Awesome! Let me know if you want some RactiveJS stickers :)

**Comment by evs-chris** [comment] 2015-03-03 15:31
There's actually a better error message for this issue in edge already. http://jsfiddle.net/qp83ozqa/

The problem is that Ractive builds a virtual DOM with the template (as opposed to just string templating), so elements have to be contiguous. You can't have ```{{#if something}}<div>{{/if}}...{{#if something}}</div>{{/if}}`` because it parses into
```
if
  div
...
if
  woops found a closing tag with no open
```

... also, it seems @martypdx beat me to it :)

**Comment by paulocoghi** [comment] 2015-03-03 16:09
@martypdx Now I understand it better!

> Awesome! Let me know if you want some RactiveJS stickers :)
Maybe it will not be possible, since I am in Brazil (Sorocaba city). But I can pay gladly the shipping and stickers costs if they are not expensive.

**Closed** 2015-03-03 16:20 UTC

**Comment by paulocoghi** [comment] 2015-03-03 17:06
@martypdx I can't find a way to open a row when `num` is even and closing it when `num` is odd (without splitting the div tags). This is bacause I have two users inside each "row":

```html
<!-- even: num is 0 here, so the "row is opened before it" -->
<div class="row"> 
	<div class="...">
		user0 content 
	</div>

<!-- odd: num is 1 here, so the div tag is closed after it" -->
	<div class="...">
		user1 content
	</div>
</div>
```

A full row would looks like this

```html
<div class="row">
	<div class="...">
		user2 content
	</div>
	<div class="...">
		user3 content
	</div>
</div>
```

And so on

```html
<div class="row">
	<div class="...">
		user4 content
	</div>
	<div class="...">
		user5 content
	</div>
</div>

<div class="row">
	<div class="...">
		user6 content
	</div>
	<div class="...">
		user7 content
	</div>
</div>
```

**Comment by martypdx** [comment] 2015-03-03 18:34
Oh right. [Here's](http://jsfiddle.net/n74zfpvu/) one approach:

```html
    {{#each users:num}}
        {{#unless (num % 2) }}
            <div class='row'>
                {{>cellContents { user: users[num] } }}
                {{>cellContents { user: users[num+1] } }}
            </div>
       {{/unless}}
    {{/each}}
```
 Otherwise, best to presort your data (using a computed property if it's going to update)
