### ISSUE TITLE
A bug of elseif

### ISSUE THREAD

**Issue by jimmyye** [ractivejs/ractive#1879] opened 2015-03-27 16:06 UTC
fiddle: http://jsfiddle.net/yue3tLoa/1/

```
r.set('list2', [1]);
r.set('list', [{a: false, b: true}]);
//r.set('list2', [1]);
```

```
    {{#each list2}}
        {{#if list[@index].a }}
            <div>list[{{@index}}].a is true</div>
        {{elseif list[@index].b }}
            <div>list[{{@index}}].b is true</div>
        {{/if}}
    {{/each}}
```

When set list2 before list, an error occurs: Failed to compute "${_1-0--b}"
only when `elseif` is in an `each` block.

**Comment by Madgvox** [comment] 2015-04-07 19:51
Looks like the elseif doesn't like the `list[@index]` part. Using `list[i]` also breaks, if you define `i` in the each block. Using a constant value, like `list[0]` does not break.

**Comment by Madgvox** [comment] 2015-04-07 23:08
Did some further investigating, when the computation is called it's not passing the value of `list` into the function getter, only the value of `@index`. I'm not familiar enough with the code to immediately know why that's happening, but I'm going to keep poking at it.

**Comment by Madgvox** [comment] 2015-10-24 06:58
As of 0.8-edge, the fiddle in the OP is throwing a `TypeError` as well as a `failed to compute` warning. I'm going to mark this as a regression bug.

**Comment by Rich-Harris** [comment] 2015-11-06 18:11
This appears to be fixed in edge now. Please reopen if not

**Comment by jimmyye** [comment] 2015-11-06 18:35
But there's a new warning:
```
Ractive.js 0.8.0-edge in debug mode, more...
ractive.js:195 Ractive.js: Failed to compute @@undefined[0]\.b: Cannot read property '0' of undefined
ractive.js:11391 show details
ractive.js:11394 TypeError: Cannot read property '0' of undefined

    @@undefined[0].b
```

**Comment by Rich-Harris** [comment] 2015-11-06 18:38
Yep. When you call `r.set('list2', [1])`, you're causing the `{{#each list2}}` sections to iterate once over `list2`, and insodoing asking Ractive to calculate the value of `list[@index].a`. Since `list` has no value, it can't do that, so it prints the warning. The `@undefined` refers to the fact that `list` doesn't exist.

**Comment by jimmyye** [comment] 2015-11-06 18:50
But the warning is about `list[@index].b` not `list[@index].a`, which occurs only because the undefined var is in a `elseif` block.

**Comment by Rich-Harris** [comment] 2015-11-06 19:14
Ah, got you. Something to do with the way inverted conditions get turned into expressions... will reopen this and see if there's a possible fix

**Comment by evs-chris** [comment] 2016-08-31 18:28
This is now fixed in edge - elseif conditions are no longer forced into being expressions.

**Closed by evs-chris** 2016-08-31 18:28 UTC
Labels: better error, regression bug
