### ISSUE TITLE
Comparing and updating aria-controls attribute in the DOM

### ISSUE THREAD

**Issue by gaelicmichael** [ractivejs/ractive#1950] opened 2015-04-29 20:26 UTC
Yet another issue from me related to a complex application in which I wrap jQueryUI widgets... and a problem due to those side-effects, I'm afraid. From what I can tell, the bug is due to the following behaviour:

My application maintains an array of configuration data which gets unravelled by templates into DOM structure, including jQueryUI widgets. In general, it looks like the DOM structure is getting updated properly EXCEPT that the old (pre-delete) IDs for jQueryUI widgets still exist in the ''aria-controls'' attribute (i.e., the IDs of DOM elements are updated properly to the new post-delete indices but not the values of the "aria-controls" attributes).

Is there some way to address this? Is there some hook in Ractive I need to attach to in order to tell it to examine this attribute, or something?

**Comment by gaelicmichael** [comment] 2015-04-29 20:33
PS. There are some relevant notes about how jQueryUI uses this attribute at:
http://stackoverflow.com/questions/16437206/jquery-ui-ajax-tab-using-aria-control-instead-of-url

**Comment by gaelicmichael** [comment] 2015-04-30 13:25
I hope that someone is interested in this issue as it will affect the use of Ractive with jQueryUI.  You can download my app from my Public Dropbox folder at:
https://www.dropbox.com/sh/xjf9veuxx8w11pa/AADx8fCPZRKpWcRBCEiJZQusa?dl=0

To see this bug in operation, do the following:
(1) Open the "Views and Filters" accordion panel.
(2) Click the "Add View/Filter" button.
(3) In the modal window, leave "Map" as the choice, enter some label, and click "OK".
(4) Do this again (to create a second Map entry)
(5) Click the trash icon on the right side of the first Map entry you created and click "OK" in the confirmation modal.
(6) Only the second Map you created will remain. Click on the "artists" tab.
(7) In your error console, you will see "Error: jQuery UI Tabs: Mismatching fragment identifier."  If you examine the DOM elements, you will see the issue I described above.

**Comment by martypdx** [comment] 2015-04-30 15:47
On line 643: `<script src="ractive.jqueryui.js"></script>` that file is not in project. If I comment that out it runs but no error. Missing file?

**Comment by gaelicmichael** [comment] 2015-04-30 15:50
Sorry about that vestige, Marty.  I just removed that reference and updated the file on DropBox, if you wouldn't mind re-downloading it!

**Comment by martypdx** [comment] 2015-04-30 15:56
It's not giving me an error @gaelicmichael :confused:

**Comment by gaelicmichael** [comment] 2015-04-30 15:58
I've tested it on FireFox 37.0.2 and Safari 8.0.5.  Did you go through the same steps I outlined above? What browser are you using?

**Comment by martypdx** [comment] 2015-04-30 15:59
> What browser are you using?

chrome

**Comment by martypdx** [comment] 2015-04-30 16:00
just tried Safari, no error. On OS X 10.9.5.

**Comment by gaelicmichael** [comment] 2015-04-30 16:02
I've just tried it on Chrome and I get the same error. If you've loaded all of my same code, why would be get two different behaviours?

**Comment by martypdx** [comment] 2015-04-30 16:03
I uploaded movie, maybe I'm doing something wrong?https://www.dropbox.com/s/un819lfd527l77k/gaelicmichael.mov?dl=0

**Comment by gaelicmichael** [comment] 2015-04-30 16:03
BTW, I'm on Mac OS 10.10.3.

**Comment by gaelicmichael** [comment] 2015-04-30 16:04
You haven't actually followed the revised steps I gave above (you might need to reload this GitHub page because I changed them from the initial description).

**Comment by gaelicmichael** [comment] 2015-04-30 16:23
@martypdx  Here are the revised steps again:
(1) Open the "Views and Filters" accordion panel.
(2) Click the "Add View/Filter" button.
(3) In the modal window, leave "Map" as the drop-down choice, enter some label (Map1), and click "OK".
(4) Click the "Add View/Filter" button, select "Cards" on the drop-down menu, enter some label (Cards1), and click "OK".
(5) Click the "Add View/Filter" button, select "Timeline" on the drop-down menu, enter some label (Time1), and click "OK".
You now see three items in the list of View/Filters.
(6) Click the up arrow on the right side of the Cards title. This will move that entry to the top of the list so the order will now be Cards, Maps, Timeline.
(7) Click the delete button (trash bin) on the right of the Cards title and confirm on the modal dialog.
(8) Now only the Map and Timeline remain (in that order). Click on the "artists" tab on the Timeline.
(9) In your error console, you will see "Error: jQuery UI Tabs: Mismatching fragment identifier." If you examine the DOM elements, you will see the issue I described above.

**Comment by martypdx** [comment] 2015-05-02 17:32
Just putting a note that this may be possibly related to #1943. Looking at your code it doesn't appear you're using `splice` without second (third ractive) argument.

**Comment by gaelicmichael** [comment] 2015-05-04 01:32
It seems strange, though, that it would only manifest in the "aria-controls" attribute of a DOM element, rather than in any other way. Is that logical, @martypdx ?

**Comment by gaelicmichael** [comment] 2015-05-28 11:57
Can you please mark this as a bug, @martypdx? If it doesn't get fixed in a revision of Ractive soon, I'll need to change my use of jQueryUI tabs to something else, which will entail a good bit of work for me. Thanks.

**Comment by MartinKolarik** [comment] 2016-03-28 20:07
Closing this as it's not a bug in Ractive.

@gaelicmichael it's been almost a year, but in case you'd like to know where the problem was, let me know and I'll post the details.

**Closed by MartinKolarik** 2016-03-28 20:07 UTC
