### ISSUE TITLE
object iteration: dots in key names

### ISSUE THREAD

**Issue by sigod** [ractivejs/ractive#1967] opened 2015-05-18 09:48 UTC
http://jsfiddle.net/sigod/v0x6qpcL/

Since object iteration is a special case I expect it can be fixed for this single case. Or if it cannot be, then library must rise warning in the console (don't forget mention it in the docs!).

Duplicate: #1100 — I opened new issue, so you won't miss it this time.
Related: #744.

**Comment by dagnelies** [comment] 2015-05-21 14:45
Just to leave my grain of salt, I think "nothing" should be done as it actually behaves correctly.

Let me explain:
1) First, ractive consider dots to be a separator, nothing new about that.
2) People often use `Ractive.set('my.nested.keypath', ...)` to set nested data. Or, for multiple updates at once: `Ractive.set({'my.nested.keypath': 1, ...})` which are both valid cases and are *expected* to resolve to nested data according to the doc. And what is `data`? It is just the data you first initialize it with.

I would find it misleading if `new Ractive({data: { /*data*/ }})` and `Ractive.set({ /*data*/ })` would behave differently. On the opposite, everything is ok the way it is. If you put whole keypaths in your data, you basically get them, which is, as expected.

**Comment by sigod** [comment] 2015-05-21 15:27
> I think "nothing" should be done

"Nothing"? What does this mean?

> ractive consider dots to be a separator, nothing new about that

Actually, it's very new for me. I don't think I ever saw such statement in the documentation. And, just checked, it isn't mentioned in Object iteration section.

**Comment by RangerMauve** [comment] 2015-05-21 15:49
I think that what @dagnelies is saying for initializing data and using `Ractive.set` isn't entirely relevant for this issue. The problem isn't so much about accessing properties that have a dot in the name, as it is more that iterating through an object isn't working properly. I think that the behavior with `Ractive.set` should be retained, but that the iteration should also work for this specific case.

**Comment by dagnelies** [comment] 2015-05-22 07:25
FYI, I was referring to:
http://docs.ractivejs.org/latest/keypaths

Perhaps a check/warning would be the most adequate if dots or special characters are present in the initial data ...but I'm not even sure I'd want that. Keypaths are the core Ractive. As @Rich-Harris mentionned in `#744`, the proper way to do it would be to use dot escaping. But honestly, I'm not fond of it either.

...well, now you know it, dots are separators, avoid them in attribute names ;)

**Comment by RangerMauve** [comment] 2015-05-22 12:00
The data isn't being mangled at all. The object structure is preserved. That's why the keys are rendering with the dot in them in the example. The issue is that the content of the object isn't being rendered properly during iteration.

**Comment by MartinKolarik** [comment] 2015-10-14 16:30
Wanted to close this, but then I noticed `{{@key}}` references now output escaped keypaths. Since these are supposed to be object keys, I think they should be unescaped. Adding `unescapeKey()` [here](https://github.com/ractivejs/ractive/blob/099c61487d76e64232fec74151a86dbc180b84c6/src/model/specials/KeyModel.js#L12) seemed to work, but I'm not sure if that's really the right approach.

On a related note, since it's no longer safe to do `keypath += '.' + key` and `keypath.split('.')`, we should probably expose public `joinKeypath()/splitKeypath()/escapeKey()/unescapeKey()` method(s).

**Comment by evs-chris** [comment] 2015-10-14 19:00
> but I'm not sure if that's really the right approach

I think it is, and I think it needs to go on `getKeypath` as well.

> we should probably expose public joinKeypath()/splitKeypath()/escapeKey()/unescapeKey() method(s)

:+1:, especially if `joinKeypath` handles ancestor movement a la the path node module ( `joinKeypath('foo.0.bar', '../..') === 'foo'` )

**Closed** 2016-04-06 05:51 UTC
Labels: enhancement
