### ISSUE TITLE
Numbers lower than 10 undefined when passed into partial's "as" context

### ISSUE THREAD

**Issue by woodlandhunter** [ractivejs/ractive#2397] opened 2016-02-23 16:54 UTC
See fiddle http://jsfiddle.net/478xdvqb/

```xml
<main></main>

<script id='template' type='text/ractive'>
    {{>test-partial 1 as numa, 10 as numb, 20 as numc}}
</script>

<script id='test-partial' type='text/ractive'>
	<div>A:  {{numa}}</div>
	<div>B:  {{numb}}</div>
  <div>C:  {{numc}}</div>
  <div>C1:  {{.numc}}</div>
</script>
```

```js
var ractive = new Ractive({
    el: 'main',
    template: '#template',
});

```

Also a secondary question regarding "as" context and using restricted `{{.keypath}}` (see the C1 line in the fiddle). Should that work?

**Comment by evs-chris** [comment] 2016-02-23 17:10
Hmmm... `numa` should work. You've run across one of those parsing bugs I keep making a note to hunt down and keep forgetting. It just won't parse a single digit literal int. You can usually work around it by adding a `+` e.g. `+1`, but when you try to do that as the first expression in a partial alias, it confuses the parser. Using `{{>partial 10 as numb, 20 as numc, +1 as numa}}` is a possible workaround.

`.numc` is not resolving as intended. Aliases don't change the context. They just add names to check on the way to resolving an ambiguous reference and `.numc` is entirely unambiguous.

**Comment by evs-chris** [comment] 2016-02-23 20:50
This is really weird... I've found the cause and I'm not sure exactly how to fix it. I didn't realize that Ractive supports this `{{#with someArray}}{{1}}{{/with}}`. So basically, numbers are always treated as references to an array member. I think that's pretty surprising, but it was done on purpose. The reason `10` and `20` work is that the `refineExpression` test for array indices is a little wonky and ignored numbers ending in `0`.

So, how to fix?

1. Fix the regex and keep the old behavior.
2. Drop the old behavior and call number literals number literals.
3. Flag the reference as a potential number literal and use the literal if not in the context of an array.

I vote 2 because on the odd (in my opinion) chance that you'd want to use a number literal as a reference in an array, you can still do `{{#with someArray}}{{.[1]}}{{/with}}`. 3 supports both existing and expected behavior, but also adds a fair amount of complexity during ambiguous resolution and creating expressions on the fly for the special reference-but-not-necessarily case. So not really csp friendly. I suppose we could add global number models to handle that, but again, complexity.

**Comment by fskreuz** [comment] 2016-02-23 21:35
> I didn't realize that Ractive supports this {{#with someArray}}{{1}}{{/with}}

This does feel a bit confusing. I'm with dropping this. Don't want Ractive to pile up with these kinds of sorcery. `{{ this[n] }}` would look nice (or as @evs-chris likes his shorthands, `{{ .[n] }}`).

**Comment by martypdx** [comment] 2016-02-23 21:51
Dropping it is consistent with js where variables cannot start with numbers.

**Comment by woodlandhunter** [comment] 2016-02-23 22:12
Does the mustache spec say anything about this or is it a Ractive specialty?

**Comment by martypdx** [comment] 2016-02-23 22:20
`{{0}}` is a valid mustache ref and a valid handlebars ref (though in straight mustache you would never have a `{{0}}` except if root object is an array because `{{#someArray}}` would iterate, not provide a context block).

**Closed** 2016-02-26 18:57 UTC
Labels: bug
