### ISSUE TITLE
Feature request: a Ractive file extension

### ISSUE THREAD

**Issue by matthew-dean** [ractivejs/ractive#2283] opened 2015-11-17 01:15 UTC
I'd love to someday add a mode to https://github.com/ajaxorg/ace/tree/master/lib/ace/mode to get proper code coloring for Ractive templates.

The only problem is: Ractive doesn't have an "official" file extension that it recommends (unlike ```.handlebars``` / ```.hbs``` for Handlebars). Since 0.8 features deviate even more from Handlebars syntax, it would be a nice-to-have. Probably simplest might be ```.ractive```, and maybe just mention that somewhere or put in a code example? Not sure.

**Comment by matthew-dean** [comment] 2015-11-17 01:17
Perfect example is https://github.com/ractivejs/ractive/issues/131, where a user is using ```.rac```, yet @Rich-Harris uses ```.html``` in his example.

**Comment by heavyk** [comment] 2015-11-17 01:22
you can set the mode based on file content for most editors (usually based on the shebang) perhaps, I dunno you could put a comment on the top of your templates `<!-- ractive -->` and if that exists, use your custom ace mode

**Comment by fskreuz** [comment] 2015-11-17 02:32
I think the issue is better expressed in the spec repo... like this -> https://github.com/ractivejs/component-spec/issues/13

**Comment by Madgvox** [comment] 2015-11-17 03:17
@fskreuz Although I agree in principle, the component-spec thread is not likely to get as many eyes on it. For the sake of discussion, I think it's fine to have here as well.

**Comment by fskreuz** [comment] 2015-12-06 02:05
Closing in favor of https://github.com/ractivejs/component-spec/issues/13

**Closed by fskreuz** 2015-12-06 02:05 UTC
Labels: enhancement
