### ISSUE TITLE
unexpected behavior when setting a keypath to an array, then an object, then back to an array

### ISSUE THREAD

**Issue by jmellicker** [ractivejs/ractive#2054] opened 2015-07-26 18:36 UTC
This pen:
http://codepen.io/jmellicker/pen/eNPrpJ?editors=101

- sets the 'products' keypath to an array (works great)
- then sets it to an object (works great)
- then sets it back to an array, but at this point the DOM only shows the last product (does not iterate through the whole list as it did initially).

My guess is that Ractive is caching in some way that prevents it from rendering properly when the keypath is set back to an array, in which case I thought you would want to know (since you all are heroically committed to finding and fixing every last anomaly in this wonderful framework).

**Comment by Rich-Harris** [comment] 2015-08-30 15:47
> since you all are heroically committed to finding and fixing every last anomaly in this wonderful framework

Now I feel bad! Apart from @MartinKolarik's PR not being merged, I just wrote this on https://github.com/ractivejs/ractive/pull/2022#issuecomment-136146828:

> fairly random stuff like `foo` in `{{#each foo}}` can't change between an array and an object, which is a mythical use case that caused code bloat

In other words I thought that used to work and that it no longer did, whereas in fact it never worked at all. 0.8 has a slightly different architecture that changes how list sections work, so the PR can't be merged. So I guess the question comes back to whether or not it is in fact a mythical use case – is there a real world need for this? Would an error message ('An `each` section (products) cannot switch from an object to an array') suffice? Am open to persuasion, I've just never encountered this need myself and am wary of adding code if it's not something we truly need. Thanks!

**Comment by martypdx** [comment] 2015-08-30 17:39
> I thought that used to work and that it no longer did, whereas in fact it never worked at all

Not sure I follow, works in latest: http://jsfiddle.net/ob9j0ker/ and there [are tests](https://github.com/ractivejs/ractive/blob/dev/test/testdeps/samples/render.js#L658-L674) now commented out. :)

I agree that the use case is very rare, but the issue is more about the consistency between data and template. Ideally, a given state produces the same template. So if this isn't supported it means that a template will cease to work as expected (in response to some new data state) because of a prior data state.

I think we can be heavy-handed and not try and reuse section fragments and force a complete re-render, which should minimize needed code.

**Comment by martypdx** [comment] 2015-08-30 17:42
> I thought that used to work and that it no longer did, whereas in fact it never worked at all
> Not sure I follow, works in latest: http://jsfiddle.net/ob9j0ker/ and there are tests now commented out. :)

Oh, I think you mean the double-switch back to the array. Got it. Still think we should support for above reasons.

**Closed** 2015-09-04 19:14 UTC
Labels: bug

**Comment by jmellicker** [comment] 2016-03-15 01:41
Totally lost track of this thread!

We ran into this due to a collection of items coming back from an API as an object, then providing a search box to search the object using the awesome Fuse search plugin, which returns an array (then just setting the display data set to the search result array).

So it was very specific to our use case. Sorry for the bike-shedding... now I feel bad! :)
