### ISSUE TITLE
Two-way binding with expressions

### ISSUE THREAD

**Issue by gushogg-blake** [ractivejs/ractive#1663] opened 2015-01-27 23:40 UTC
I realise that two-way binding with expressions is explicitly not supported, but I'm using it for setting the label (value attribute) of a submit button with a call to an i18n function.  There is no need for it to be bound both ways, as the user can't change the value.

This is throwing an uncaught exception which ends up breaking the rest of the template in some of my code.

You can see the error in the console if you run this fiddle, and then focus in and out of the textbox: http://jsfiddle.net/3gweh8t9/

Here is the issue relating to the actual problem it's causing: https://github.com/jsonchess/lightsquare/issues/115

**Comment by Rich-Harris** [comment] 2015-01-28 00:01
Oh, that's annoying. Adding the bug label. You can get around it with `twoway: false`, though for some reason you have to apply it at the instance level, applying it at the element level (with a `twoway='false'` attribute) doesn't appear to work for whatever reason. So it looks like this is a twofer.

Demo of it working with `twoway: false`: http://jsfiddle.net/42a4a822/

**Comment by Rich-Harris** [comment] 2015-01-28 00:16
Ok, so it turns out that this is fixed in edge (here's a [fork of your fiddle](http://jsfiddle.net/dst7capk/), using the edge build). With the `twoway='false'` the console warning is suppressed, but either way it's recognised as unbindable, and that error never appears.

Are you able to use the edge build in your project? If not, disabling twoway binding at the instance level (with `twoway: false`) is probably your best bet.

**Comment by anywhichway** [comment] 2015-01-30 15:21
I am getting "Two-way binding does not work with expressions" and Uncaught TypeError: Cannot read property 'split' of undefined using "latest" from the cdn. 

I am not using Ractive expressions anywhere, although the interpolator obviously creates something from my code that looks like an expression. See line 8722 of ractive.js:

`if ( interpolator.keypath && interpolator.keypath.substr( 0, 2 ) === '${' ) {
				warn( 'Two-way binding does not work with expressions (`' + interpolator.keypath.slice( 2, -1 ) + '`)' );
				return false;
			}`

The problem only occurs if I use my objects in a nested template. If I elevate them to the top level and put the template code inline, the problem goes away. So, if seems like it has something to do with Ractive copying my objects into lower scopes.

Some of objects do have data in them that looks syntactically similar to ractive expressions, e.g.
`{
    grossProfit: {type: "number", calculate: "{salesPrice} - {costOfGoods}"}
}`

However, the issue also shows up when I use regular functions that get "compiled" into objects. In fact, the above expression actually gets converted into a function similar to that below which also causes the Ractive error:

`Product.prototype.amazonOutboundShippingWeight = function() {
		return function(shippingWeight,isMedia,dimensionalWeight,amazonStandardOrOversize,amazonSizeTier) {
			if(isMedia) {
				return shippingWeight + 0.125;
			}
			if(amazonStandardOrOversize==="Standard" && shippingWeight<=1) {
				return shippingWeight + 0.25;
			}
			if(amazonStandardOrOversize==="Standard" && shippingWeight>1) {
				return Math.max(shippingWeight,dimensionalWeight) + 0.25;
			}
			if(amazonSizeTier==="SPL OVER") {
				return shippingWeight + 1;
			}
			return Math.max(shippingWeight,dimensionalWeight) + 1;
		}(this.shippingWeight,this.isMedia,this.dimensionalWeight,this.amazonStandardOrOversize,this.amazonSizeTier) 
	}`

If I use the Ractive "edge" build the problem goes way, but the code is slow as molasses. Things that updated sub-second before now take 3 to 5 seconds. 

Also note, the two way error is truncating key names in its report, note the "t" missing below:

"Two-way binding does not work with expressions ({object:model-productCalculator,property:"amazonFBANetProfit",options:model-productCalculator-class-properties-"amazonFBANetProfit"-}}.object.amazonFBANetProfi)"

**Comment by anywhichway** [comment] 2015-01-30 15:35
I tried setting two-way:false which does eliminate the error; however, that also breaks our application since we need the two way binding. I am suspicious that Ractive is interpretting any other library redefining data properties using Object.define property to use gettters and setters as an instance of its own redefinition rather that checking the get and set functions to see if they are the ones Ractive has set or perhaps those set by another library. Note in our case, the other library does the re-definition before Ractive gets hold of the objects. Just speculation ...

**Comment by martypdx** [comment] 2015-01-30 15:48
@anywhichway - functions count as a expressions, as do computed properties. The change in `edge` is to allow properties of objects _returned from expressions_ to be two-way bindable. Ractive represents expressions in keypaths as `${ expression }` (hence the trimming of the final character for the error message). So the new code looks at the _end_ of the keypath, not the begining, allowing `${ expression}.foo` but not `${ expression }`.

> If I use the Ractive "edge" build the problem goes way, but the code is slow as molasses. Things that updated sub-second before now take 3 to 5 seconds.

Egads, that's no good. Anything you can do to provide an example or otherwise help us understand what's going on would be appreciated. Are you using `magic: true` by any chance? I suspect you might be based on comment below.

> I am suspicious that Ractive is interpretting any other library redefining data properties using Object.define property to use gettters and setters as an instance of its own redefinition rather that checking the get and set functions to see if they are the ones Ractive has set or perhaps those set by another library. Note in our case, the other library does the re-definition before Ractive gets hold of the objects. Just speculation ...

I had some problems with this on the array modifiers. Ractive uses `Array.prototype.method.call` rather than respecting the object prototype hierarchy.  Again, if you could produce a fiddle showing the issue that would be helpful.

**Comment by anywhichway** [comment] 2015-01-30 16:22
Thanks for such a quick response! 

Regarding: "functions count as a expressions, as do computed properties". Do you count the end state of foo below below as function and or expression? (Note, this is highly simplified code just to get an answer to this question).

var o = { foo: 1 };
var fooprop = Object.getOwnPropertyDescriptor(o,"foo");
var get = function() { return get.value }
var set = function(value) { return get.value = value; }
delete prop.value;
fooprop .get = get;
fooprop .set = set;
Object.defineProperty(o,fooprop );

Fiddle will be hard due to the use of the other library that uses Object.define to create objects that are reactive in nature. We use the other library because it focuses exclusively on creating reactive objects and is somewhat more powerful, e.g. computations are part of the objects rather than split into a parrallel tree as in Ractive and can also be expressed as strings or full on Javascript functions which behave as normal functions until an object is actived (very useful for semantic testing and debugging). And, reactive code can be added and removed just like with Object.observer. I'll see what I can do.

Yes, I am using magic ... which is as it says MAGIC! Hundreds of fewer lines of code. Which is also why we are using the other reactive library.

Any reason you can think of that our code would work so long as we are not using nested template calls?

**Comment by martypdx** [comment] 2015-01-30 22:00
Basically if the reference as additional syntax characters beyond the reference, outside of `.` and `[x]`, it counts as an expression: `{{ foo + bar }}`, `{{ fn() }}`, etc. So it's not that it's a function per se, it's the invocation (`()`).

[This PR](https://github.com/ractivejs/ractive/pull/1577) moved the magic mode adaptors out of the core code. I haven't had a chance to really look at that, so I don't know if that might be part of the issue you're experiencing.

**Comment by anywhichway** [comment] 2015-01-31 10:52
Thanks, for response. We are not doing either {{ foo + bar }}, {{ fn() }} in our code. Continuing with my simple example from above we are just doing {{foo}}. I'll try put my simple example in a Fiddle and see if it has the sam effect.

**Comment by gushogg-blake** [comment] 2015-01-31 13:44
Using the edge build resolves my issue, thanks - setting the URL in bower.json to git://github.com/ractivejs/ractive.git#edge seems to work.

**Comment by anywhichway** [comment] 2015-02-01 13:16
We re-wrote the backend reactive library we are using and whatever caused Ractive to identify our contents as patterns when they were not has disappeared. Yay! Still running slow as molasses, actually more like a glacier now. But, we have a hypothesis .... When going about its re-redendering does Ractive re-create objects referenced on the page and in the data section of config? If so, this would explain our problem. One of the objects we use has a very high creation cost, although we only create one instance of it. We ran the JS profiler in Chrome on our own unit test and get a total of 4ms execution time for a function that is called from within our constructor. When we run the profiler on the Ractive page where we construct a single instance inside of the data section of config the same function has a total execution time of 23,918.2ms! The object does some complex calculations with many cascading impacts and several hundred updates to its own internal reactive state would not be unexpected based on a single change to an input. All of the impacted fields are part of the render state in the Ractive page. Our unit test making the same input data change runs in 2ms.

**Comment by anywhichway** [comment] 2015-02-01 23:09
We have created a workaround which is probably a generically useful pattern. Rather than put our entire object into the Ractive config, we create a proxy which is just dumb data fields, we then relay information back to our "intelligent" object using a ractive observer, e.g.:

`ractive.observe('model.productCalculator.*',function(newValue,oldValue,keypath) {
	var path = keypath.split(".");
	var key = path.pop();
	ProductCalculator[key] = newValue;
});`

The "intelligent" object knows the path to the dumb data in the Ractive config and updates it as part of its own dependency graph.

Given this provides some nice separation of interests and that we are probably a pretty special case, you can stop pursuing our concerns further if you wish.

We have been unable to create a simple Fiddle. We will provide more detail if requested.

Thanks for such a great library for driving our UI!

**Comment by Rich-Harris** [comment] 2015-02-01 23:43
@anywhichway if you *do* manage to whittle it down to a JSFiddle it would be very helpful - afraid it's hard to know what the issue might be without being able to see what the other library is doing. It sounds like it's not a performance *regression*, per se, but rather something that would probably have been slow with the `latest` build if it worked at all. Either way it sounds bad!

By the way, when including code snippets in GitHub comments you can use backticks to mark out a code block, like so:

```html
<p>here is some HTML</p>
```

```js
console.log( 'here is some JavaScript' );
```

![screen shot 2015-02-01 at 18 41 31](https://cloud.githubusercontent.com/assets/1162160/5994457/040f9fe8-aa42-11e4-98cd-c361508402c3.png)

It makes it much easier to follow :) I took the liberty of adjusting your earlier comments by way of demonstration. 'GitHub Flavoured Markdown' has a few tricks like that - [some useful docs here if you're interested](https://help.github.com/articles/github-flavored-markdown/)

**Comment by Rich-Harris** [comment] 2015-02-01 23:45
I'll close this issue as the original issue has been solved (if hacking bower config to paper over the lack of a recent release counts as 'solved'...) - @anywhichway would you mind opening a fresh issue if you can isolate the problem you were having? Thanks

**Closed by Rich-Harris** 2015-02-01 23:45 UTC
Labels: bug, pending-clarification

**Comment by evs-chris** [comment] 2015-02-02 00:07
FWIW, in Chrome, I've found that having dev tools open when doing anything with even mildly complex Ractive components makes everything **much** slower. In my case, the difference is ~0.5s closed to 5s open. I don't know where else that applies, but it can be quite disconcerting. I spent the better part of a day trying to track it down, but I never found anything specific in Ractive that was causing it.

**Comment by anywhichway** [comment] 2015-02-02 13:39
Hah ... I consistently use backticks; however, I had been using them wrong (did not put the language prefix)!

Will open another issue if I can isolate.

Posting a fiddle that shows the principle of the backend reactive code (alothough it is a hard coded case rather than being abstract):

http://jsfiddle.net/anywhichway/8044fm91/42/

Posting the proxy code since it is generally useful. This is as fast as our unit test cases even with Ractive wrappers. 

Note, the object being proxied must provide an onChange handler which takes a property to monitor and the callback to make when it changes, in this case updating a Ractive data element.

```js
function addProxy(ractive,keypath,instance,properties) {
	var proxy = {};
	properties || (properties = Object.keys(instance));
	properties.forEach(function(property) {
		proxy[property] = instance[property];
		instance.onChange(property,function(value) {
			var path = keypath+"."+property;
			var currentvalue = ractive.get(path);
			if(currentvalue!=value) {
				ractive.set(keypath+"."+property,value);
			}
		});
	});
	ractive.observe(keypath+".*",function(newValue,oldValue,keypath) {
			var path = keypath.split(".");
			var key = path.pop();
			if(instance[key]!=newValue) {
				instance[key] = newValue;
			}
		});
	ractive.set(keypath,proxy);
}```
