### ISSUE TITLE
Event.context gives unwrapped object instead of wrapped object

### ISSUE THREAD

**Issue by tcunnington** [ractivejs/ractive#1909] opened 2015-04-09 02:34 UTC
I am seeing an issue that started upon upgrading to 0.7.2. It only happens with my code that uses Backbone models, but I believe it would be a problem for any wrapped object.

Prior to the upgrade when a proxy event fired and was picked up by an event handler the value of e.context was the backbone model itself. Now it is the value of the attributes (the "unwrapped" value). We have been relying on this method to get the actual model so that we can use custom methods on the model. 

It looks like the problem is in Viewmodel$get. There, once a value is found for a keypath there is an if statement that decides whether the value is wrapped and if it should be unwrapped. In 0.7.2 is looks at !options.noUnwrap, whereas 0.6.1 looks options.evaluateWrapped. 
I thought I could solve my problem by setting options.noUnwrap but there doesn't appear to be any way to set it as this method is called from the genericHandler and it does not pass in an options object.

Is this intended? This appears to be a breaking change but was not listed in the changelog. This seems like the possibly relevant line:
>ractive.data is no longer available. Use ractive.get() to get a shallow copy of the data with any component mappings.

But to me this does not imply the behavior I noted above. Was it meant to?

**Comment by tcunnington** [comment] 2015-04-13 23:15
Updated the description to be more clear. Dn't know if it is legitimately an "issue" or if I just missed something. Guidance on this issue would be appreciated!

**Comment by martypdx** [comment] 2015-04-13 23:21
AFAIK we broke that unknowingly didn't intentionally mean to change that behavior for the `0.7` release - so I've marked as bug.

**Comment by sandermarechal** [comment] 2015-04-20 09:58
Is there a workaround for this bug? I'm not above forking and patching until this is properly solved. I am using ractive-backbone and this bug is a showstopper for me. I can't revert my project to Ractive 0.6.x.

**Comment by tcunnington** [comment] 2015-04-20 18:53
It looks like in the mean time you can get the value of e.context by doing `var model = this.get(event.keypath)`

However I decided to instead alter my templates to explicitly pass in the model: `on-click="myEvent:{{this}}"`
and correspondingly changed my event handler like so:
```javascript
function(e, model) {
    // ... stuff
}
```
Slightly more work but it is more declarative.

**Comment by sandermarechal** [comment] 2015-04-21 07:43
@tcunnington Thank you

**Comment by Rich-Harris** [comment] 2015-12-06 18:56
Looks like this is behaving correctly in 0.8 – will close

**Closed by Rich-Harris** 2015-12-06 18:56 UTC
Labels: bug

**Comment by mindgamesru** [comment] 2017-02-03 14:39
Looks like not, just got the same issue.

**Comment by evs-chris** [comment] 2017-02-04 02:54
@mindgamesru this issue doesn't have a reproduction. Could you open a new issue with a repro so we can get a good regression test in place?
