### ISSUE TITLE
Cannot read property 'str' of undefined with mapped properties and twoway binding

### ISSUE THREAD

**Issue by smoldaner** [ractivejs/ractive#1962] opened 2015-05-12 10:24 UTC
I created a [fiddle](https://jsfiddle.net/9egd5mmg/5/). Tested both with edge and latest, same exception.

The exception occurs in src/viewmodel/prototype/get.js, because the keypath is empty. This does not occure if I use the correct keypath "mydata.map[prop]" or without twoway binding.

**Comment by Madgvox** [comment] 2015-05-12 10:51
Hmm... I wasn't getting an error, but I was getting an 'ambiguous binding' warning in the console. I was able to fix this error by de-ambiguousing the keypath: http://jsfiddle.net/9djx8vb5/

Update: So I just tested it in chrome, and it looks like for some reason in chrome, an ambiguous two-way binding reference does not properly display the warning and instead throws a cryptic error. So the real meaning of this error is that you're binding an ambiguous keypath to the input, and that you should be more specific with the keypath to prevent unexpected behavior. 

The warning message should be fixed in chrome, so I'm marking this with `better error`, but your actual issue is the ambiguous keypath.

**Comment by smoldaner** [comment] 2015-05-12 12:52
Yes, it appears in chrome. And yes, a better error message could save a lot of time finding the ambiguous keypath in an application.

**Comment by Madgvox** [comment] 2015-05-13 22:07
I looked into the issue more closely and this is a bug, not just an incorrect error. The ambiguous keypath section of `Binding.js` attempts to force a resolution, but it returns an `undefined` keypath. That undefined keypath gets sent to the `viewmodel.get()` function, which errors out because the keypath is undefined. I don't know why firefox isn't throwing an error because it should be. Something is going wrong in `forceResolution` which is preventing the keypath from getting resolved properly.

**Comment by Madgvox** [comment] 2015-10-24 06:48
This has been fixed in 0.8-edge.

**Closed by Madgvox** 2015-10-24 06:48 UTC
Labels: bug

**Comment by mrjoelkemp** [comment] 2016-01-06 21:11
I seem to be encountering this bug. I can't jump to 0.8-edge on my project, but was hoping that the patch could be identified so that I could possibly (hopefully) apply it to 0.7.3. 

@Madgvox any chance you could either point me to the PR or lines that fix the bug or give some advice on a 0.7.3 fix for this? Thanks a ton in advance.

**Comment by Madgvox** [comment] 2016-01-06 22:43
@mrjoelkemp I'm afraid that 0.8 was a huge refactoring of the codebase. That this bug was fixed in 0.8 is a symptom of creating a more robust core library rather than a specific patch. That's why I did not specify a PR in my closing comment. 

In 0.7, the workaround is the same; remove ambiguous bindings from your templates.

**Comment by mrjoelkemp** [comment] 2016-01-07 02:30
Thanks @Madgvox. I was pretty sure my bindings weren't ambiguous since the keypath is available `onconfig`. I'll dig a bit deeper to see and supply a fiddle if I can't figure it out.

Thanks again.

**Comment by darylteo** [comment] 2016-08-05 05:22
Suffering from the same problem here. I'm not really sure what is meant by ambiguous keypaths. Really can't see what's wrong. 

I've managed to work around this by avoiding double binding and using `<Component src={{{someobject.property}}} />` and it seems to be working for me so far. I think.

**Comment by fskreuz** [comment] 2016-08-06 02:02
When a keypath is not found in the current context, [Ractive has the ability to "climb"](http://docs.ractivejs.org/latest/references) up the data until it finds a key that matches and displays that key's data. 

```
{
  foo: 'hello',
  bar: ['world1', 'world2']
}

{{#bar}}
  {{foo}}{{this}} // We're in the context of bar, but we let Ractive climb to get foo outside bar.
{{/}}
```

Ambiguous keypaths are keypaths that don't exist in the data during initialization of a component. Because of this, Ractive has to resolve on the fly, which is a performance drawback. It can also lead to unexpected values, depending on how you structure the data.

To make a keypath unambiguous, you can define the data on the component so that the path exists on initialization. Another way is to use [restricted references](http://docs.ractivejs.org/latest/references#restricted-references), which tells Ractive not to "climb" when the keypath isn't present and resolve to `undefined` immediately.
