### ISSUE TITLE
File type inputs Warning to console 

### ISSUE THREAD

**Issue by evaneaston** [ractivejs/ractive#3019] opened 2017-06-26 20:00 UTC
I'm in the process up updating a ractive 0.7.3 app to 0.9.1 and when selecting "Choose File" on file type inputs, I'm seeing the following exception on the console in Chrome 58.

> DOMException: Failed to set the 'value' property on 'HTMLInputElement': This input element accepts a filename, which may only be programmatically set to the empty string.

Everything functions properly, but in the interests of having a warning- and error- free console this is undesirable.  It wasn't happening in 0.7.3 and I know changes were made in 0.8.x.

Here's [a minimal codepen](https://codepen.io/eeaston/pen/dRZyGa?editors=1111) demonstrating the issue.  Open it in chrome, open the developer console, then select "Choose File".

**Comment by ghost** [comment] 2017-06-26 20:59
Duplicate of https://github.com/ractivejs/ractive/issues/3015

**Closed as completed by ghost** 2017-06-26 20:59 UTC
Labels: no action/duplicate
